/**
 * TravelTime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.ResponseDistanceBreakdownItem;
import org.openapitools.client.model.ResponseFares;
import org.openapitools.client.model.ResponseRoute;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ResponseTimeFilterProperties {
  
  @SerializedName("travel_time")
  private Integer travelTime = null;
  @SerializedName("distance")
  private Integer distance = null;
  @SerializedName("distance_breakdown")
  private List<ResponseDistanceBreakdownItem> distanceBreakdown = null;
  @SerializedName("fares")
  private ResponseFares fares = null;
  @SerializedName("route")
  private ResponseRoute route = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTravelTime() {
    return travelTime;
  }
  public void setTravelTime(Integer travelTime) {
    this.travelTime = travelTime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getDistance() {
    return distance;
  }
  public void setDistance(Integer distance) {
    this.distance = distance;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<ResponseDistanceBreakdownItem> getDistanceBreakdown() {
    return distanceBreakdown;
  }
  public void setDistanceBreakdown(List<ResponseDistanceBreakdownItem> distanceBreakdown) {
    this.distanceBreakdown = distanceBreakdown;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ResponseFares getFares() {
    return fares;
  }
  public void setFares(ResponseFares fares) {
    this.fares = fares;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ResponseRoute getRoute() {
    return route;
  }
  public void setRoute(ResponseRoute route) {
    this.route = route;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseTimeFilterProperties responseTimeFilterProperties = (ResponseTimeFilterProperties) o;
    return (this.travelTime == null ? responseTimeFilterProperties.travelTime == null : this.travelTime.equals(responseTimeFilterProperties.travelTime)) &&
        (this.distance == null ? responseTimeFilterProperties.distance == null : this.distance.equals(responseTimeFilterProperties.distance)) &&
        (this.distanceBreakdown == null ? responseTimeFilterProperties.distanceBreakdown == null : this.distanceBreakdown.equals(responseTimeFilterProperties.distanceBreakdown)) &&
        (this.fares == null ? responseTimeFilterProperties.fares == null : this.fares.equals(responseTimeFilterProperties.fares)) &&
        (this.route == null ? responseTimeFilterProperties.route == null : this.route.equals(responseTimeFilterProperties.route));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.travelTime == null ? 0: this.travelTime.hashCode());
    result = 31 * result + (this.distance == null ? 0: this.distance.hashCode());
    result = 31 * result + (this.distanceBreakdown == null ? 0: this.distanceBreakdown.hashCode());
    result = 31 * result + (this.fares == null ? 0: this.fares.hashCode());
    result = 31 * result + (this.route == null ? 0: this.route.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseTimeFilterProperties {\n");
    
    sb.append("  travelTime: ").append(travelTime).append("\n");
    sb.append("  distance: ").append(distance).append("\n");
    sb.append("  distanceBreakdown: ").append(distanceBreakdown).append("\n");
    sb.append("  fares: ").append(fares).append("\n");
    sb.append("  route: ").append(route).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
