"""
    TravelTime API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.2.3
    Contact: support@igeolise.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.request_time_filter_postcode_districts_property import RequestTimeFilterPostcodeDistrictsProperty


class TestRequestTimeFilterPostcodeDistrictsProperty(unittest.TestCase):
    """RequestTimeFilterPostcodeDistrictsProperty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestTimeFilterPostcodeDistrictsProperty(self):
        """Test RequestTimeFilterPostcodeDistrictsProperty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestTimeFilterPostcodeDistrictsProperty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
