/*
 * TravelTime API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.1
 * Contact: support@igeolise.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RequestTimeFilterPostcodeDistrictsProperty string

// List of RequestTimeFilterPostcodeDistrictsProperty
const (
	TRAVEL_TIME_REACHABLE RequestTimeFilterPostcodeDistrictsProperty = "travel_time_reachable"
	TRAVEL_TIME_ALL RequestTimeFilterPostcodeDistrictsProperty = "travel_time_all"
	COVERAGE RequestTimeFilterPostcodeDistrictsProperty = "coverage"
)
