# TravelTime API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.2.2
# Contact: support@igeolise.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RequestRoutes
#'
#' @description RequestRoutes Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field locations  list( \link{RequestLocation} ) 
#'
#' @field departure_searches  list( \link{RequestRoutesDepartureSearch} ) [optional]
#'
#' @field arrival_searches  list( \link{RequestRoutesArrivalSearch} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RequestRoutes <- R6::R6Class(
  'RequestRoutes',
  public = list(
    `locations` = NULL,
    `departure_searches` = NULL,
    `arrival_searches` = NULL,
    initialize = function(
        `locations`, `departure_searches`=NULL, `arrival_searches`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`locations`)) {
        stopifnot(is.vector(`locations`), length(`locations`) != 0)
        sapply(`locations`, function(x) stopifnot(R6::is.R6(x)))
        self$`locations` <- `locations`
      }
      if (!is.null(`departure_searches`)) {
        stopifnot(is.vector(`departure_searches`), length(`departure_searches`) != 0)
        sapply(`departure_searches`, function(x) stopifnot(R6::is.R6(x)))
        self$`departure_searches` <- `departure_searches`
      }
      if (!is.null(`arrival_searches`)) {
        stopifnot(is.vector(`arrival_searches`), length(`arrival_searches`) != 0)
        sapply(`arrival_searches`, function(x) stopifnot(R6::is.R6(x)))
        self$`arrival_searches` <- `arrival_searches`
      }
    },
    toJSON = function() {
      RequestRoutesObject <- list()
      if (!is.null(self$`locations`)) {
        RequestRoutesObject[['locations']] <-
          lapply(self$`locations`, function(x) x$toJSON())
      }
      if (!is.null(self$`departure_searches`)) {
        RequestRoutesObject[['departure_searches']] <-
          lapply(self$`departure_searches`, function(x) x$toJSON())
      }
      if (!is.null(self$`arrival_searches`)) {
        RequestRoutesObject[['arrival_searches']] <-
          lapply(self$`arrival_searches`, function(x) x$toJSON())
      }

      RequestRoutesObject
    },
    fromJSON = function(RequestRoutesJson) {
      RequestRoutesObject <- jsonlite::fromJSON(RequestRoutesJson)
      if (!is.null(RequestRoutesObject$`locations`)) {
        self$`locations` <- ApiClient$new()$deserializeObj(RequestRoutesObject$`locations`, "array[RequestLocation]", loadNamespace("openapi"))
      }
      if (!is.null(RequestRoutesObject$`departure_searches`)) {
        self$`departure_searches` <- ApiClient$new()$deserializeObj(RequestRoutesObject$`departure_searches`, "array[RequestRoutesDepartureSearch]", loadNamespace("openapi"))
      }
      if (!is.null(RequestRoutesObject$`arrival_searches`)) {
        self$`arrival_searches` <- ApiClient$new()$deserializeObj(RequestRoutesObject$`arrival_searches`, "array[RequestRoutesArrivalSearch]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`locations`)) {
        sprintf(
        '"locations":
        [%s]
',
        paste(sapply(self$`locations`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`departure_searches`)) {
        sprintf(
        '"departure_searches":
        [%s]
',
        paste(sapply(self$`departure_searches`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`arrival_searches`)) {
        sprintf(
        '"arrival_searches":
        [%s]
',
        paste(sapply(self$`arrival_searches`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RequestRoutesJson) {
      RequestRoutesObject <- jsonlite::fromJSON(RequestRoutesJson)
      self$`locations` <- ApiClient$new()$deserializeObj(RequestRoutesObject$`locations`, "array[RequestLocation]", loadNamespace("openapi"))
      self$`departure_searches` <- ApiClient$new()$deserializeObj(RequestRoutesObject$`departure_searches`, "array[RequestRoutesDepartureSearch]", loadNamespace("openapi"))
      self$`arrival_searches` <- ApiClient$new()$deserializeObj(RequestRoutesObject$`arrival_searches`, "array[RequestRoutesArrivalSearch]", loadNamespace("openapi"))
      self
    }
  )
)

