# TravelTime API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.2.2
# Contact: support@igeolise.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RequestTimeFilterPostcodeDistricts
#'
#' @description RequestTimeFilterPostcodeDistricts Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field departure_searches  list( \link{RequestTimeFilterPostcodeDistrictsDepartureSearch} ) [optional]
#'
#' @field arrival_searches  list( \link{RequestTimeFilterPostcodeDistrictsArrivalSearch} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RequestTimeFilterPostcodeDistricts <- R6::R6Class(
  'RequestTimeFilterPostcodeDistricts',
  public = list(
    `departure_searches` = NULL,
    `arrival_searches` = NULL,
    initialize = function(
        `departure_searches`=NULL, `arrival_searches`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`departure_searches`)) {
        stopifnot(is.vector(`departure_searches`), length(`departure_searches`) != 0)
        sapply(`departure_searches`, function(x) stopifnot(R6::is.R6(x)))
        self$`departure_searches` <- `departure_searches`
      }
      if (!is.null(`arrival_searches`)) {
        stopifnot(is.vector(`arrival_searches`), length(`arrival_searches`) != 0)
        sapply(`arrival_searches`, function(x) stopifnot(R6::is.R6(x)))
        self$`arrival_searches` <- `arrival_searches`
      }
    },
    toJSON = function() {
      RequestTimeFilterPostcodeDistrictsObject <- list()
      if (!is.null(self$`departure_searches`)) {
        RequestTimeFilterPostcodeDistrictsObject[['departure_searches']] <-
          lapply(self$`departure_searches`, function(x) x$toJSON())
      }
      if (!is.null(self$`arrival_searches`)) {
        RequestTimeFilterPostcodeDistrictsObject[['arrival_searches']] <-
          lapply(self$`arrival_searches`, function(x) x$toJSON())
      }

      RequestTimeFilterPostcodeDistrictsObject
    },
    fromJSON = function(RequestTimeFilterPostcodeDistrictsJson) {
      RequestTimeFilterPostcodeDistrictsObject <- jsonlite::fromJSON(RequestTimeFilterPostcodeDistrictsJson)
      if (!is.null(RequestTimeFilterPostcodeDistrictsObject$`departure_searches`)) {
        self$`departure_searches` <- ApiClient$new()$deserializeObj(RequestTimeFilterPostcodeDistrictsObject$`departure_searches`, "array[RequestTimeFilterPostcodeDistrictsDepartureSearch]", loadNamespace("openapi"))
      }
      if (!is.null(RequestTimeFilterPostcodeDistrictsObject$`arrival_searches`)) {
        self$`arrival_searches` <- ApiClient$new()$deserializeObj(RequestTimeFilterPostcodeDistrictsObject$`arrival_searches`, "array[RequestTimeFilterPostcodeDistrictsArrivalSearch]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`departure_searches`)) {
        sprintf(
        '"departure_searches":
        [%s]
',
        paste(sapply(self$`departure_searches`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`arrival_searches`)) {
        sprintf(
        '"arrival_searches":
        [%s]
',
        paste(sapply(self$`arrival_searches`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RequestTimeFilterPostcodeDistrictsJson) {
      RequestTimeFilterPostcodeDistrictsObject <- jsonlite::fromJSON(RequestTimeFilterPostcodeDistrictsJson)
      self$`departure_searches` <- ApiClient$new()$deserializeObj(RequestTimeFilterPostcodeDistrictsObject$`departure_searches`, "array[RequestTimeFilterPostcodeDistrictsDepartureSearch]", loadNamespace("openapi"))
      self$`arrival_searches` <- ApiClient$new()$deserializeObj(RequestTimeFilterPostcodeDistrictsObject$`arrival_searches`, "array[RequestTimeFilterPostcodeDistrictsArrivalSearch]", loadNamespace("openapi"))
      self
    }
  )
)

