# TravelTime Platform API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Contact: support@igeolise.com
# Generated by: https://openapi-generator.tech


#' ResponseTimeFilter Class
#'
#' @field results 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ResponseTimeFilter <- R6::R6Class(
  'ResponseTimeFilter',
  public = list(
    `results` = NULL,
    initialize = function(`results`, ...){
      local.optional.var <- list(...)
      if (!missing(`results`)) {
        stopifnot(is.vector(`results`), length(`results`) != 0)
        sapply(`results`, function(x) stopifnot(R6::is.R6(x)))
        self$`results` <- `results`
      }
    },
    toJSON = function() {
      ResponseTimeFilterObject <- list()
      if (!is.null(self$`results`)) {
        ResponseTimeFilterObject[['results']] <-
          sapply(self$`results`, function(x) x$toJSON())
      }

      ResponseTimeFilterObject
    },
    fromJSON = function(ResponseTimeFilterJson) {
      ResponseTimeFilterObject <- jsonlite::fromJSON(ResponseTimeFilterJson)
      if (!is.null(ResponseTimeFilterObject$`results`)) {
        self$`results` <- sapply(ResponseTimeFilterObject$`results`, function(x) {
          resultsObject <- ResponseTimeFilterResult$new()
          resultsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          resultsObject
        })
      }
    },
    toJSONString = function() {
      sprintf(
        '{
           "results":
             [%s]
        }',
        paste(unlist(lapply(self$`results`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE))), collapse=",")
      )
    },
    fromJSONString = function(ResponseTimeFilterJson) {
      ResponseTimeFilterObject <- jsonlite::fromJSON(ResponseTimeFilterJson)
      data.frame <- ResponseTimeFilterObject$`results`
      self$`results` <- vector("list", length = nrow(data.frame))
      for (row in 1:nrow(data.frame)) {
          results.node <- ResponseTimeFilterResult$new()
          results.node$fromJSON(jsonlite::toJSON(data.frame[row,,drop = TRUE], auto_unbox = TRUE))
          self$`results`[[row]] <- results.node
      }
      self
    }
  )
)
