# TravelTime Platform API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Contact: support@igeolise.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ResponseBox
#' @description ResponseBox Class
#' @format An \code{R6Class} generator object
#' @field min_lat  numeric 
#'
#' @field max_lat  numeric 
#'
#' @field min_lng  numeric 
#'
#' @field max_lng  numeric 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ResponseBox <- R6::R6Class(
  'ResponseBox',
  public = list(
    `min_lat` = NULL,
    `max_lat` = NULL,
    `min_lng` = NULL,
    `max_lng` = NULL,
    initialize = function(`min_lat`, `max_lat`, `min_lng`, `max_lng`, ...){
      local.optional.var <- list(...)
      if (!missing(`min_lat`)) {
        stopifnot(is.numeric(`min_lat`), length(`min_lat`) == 1)
        self$`min_lat` <- `min_lat`
      }
      if (!missing(`max_lat`)) {
        stopifnot(is.numeric(`max_lat`), length(`max_lat`) == 1)
        self$`max_lat` <- `max_lat`
      }
      if (!missing(`min_lng`)) {
        stopifnot(is.numeric(`min_lng`), length(`min_lng`) == 1)
        self$`min_lng` <- `min_lng`
      }
      if (!missing(`max_lng`)) {
        stopifnot(is.numeric(`max_lng`), length(`max_lng`) == 1)
        self$`max_lng` <- `max_lng`
      }
    },
    toJSON = function() {
      ResponseBoxObject <- list()
      if (!is.null(self$`min_lat`)) {
        ResponseBoxObject[['min_lat']] <-
          self$`min_lat`
      }
      if (!is.null(self$`max_lat`)) {
        ResponseBoxObject[['max_lat']] <-
          self$`max_lat`
      }
      if (!is.null(self$`min_lng`)) {
        ResponseBoxObject[['min_lng']] <-
          self$`min_lng`
      }
      if (!is.null(self$`max_lng`)) {
        ResponseBoxObject[['max_lng']] <-
          self$`max_lng`
      }

      ResponseBoxObject
    },
    fromJSON = function(ResponseBoxJson) {
      ResponseBoxObject <- jsonlite::fromJSON(ResponseBoxJson)
      if (!is.null(ResponseBoxObject$`min_lat`)) {
        self$`min_lat` <- ResponseBoxObject$`min_lat`
      }
      if (!is.null(ResponseBoxObject$`max_lat`)) {
        self$`max_lat` <- ResponseBoxObject$`max_lat`
      }
      if (!is.null(ResponseBoxObject$`min_lng`)) {
        self$`min_lng` <- ResponseBoxObject$`min_lng`
      }
      if (!is.null(ResponseBoxObject$`max_lng`)) {
        self$`max_lng` <- ResponseBoxObject$`max_lng`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`min_lat`)) {
        sprintf(
        '"min_lat":
          %d
                ',
        self$`min_lat`
        )},
        if (!is.null(self$`max_lat`)) {
        sprintf(
        '"max_lat":
          %d
                ',
        self$`max_lat`
        )},
        if (!is.null(self$`min_lng`)) {
        sprintf(
        '"min_lng":
          %d
                ',
        self$`min_lng`
        )},
        if (!is.null(self$`max_lng`)) {
        sprintf(
        '"max_lng":
          %d
                ',
        self$`max_lng`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ResponseBoxJson) {
      ResponseBoxObject <- jsonlite::fromJSON(ResponseBoxJson)
      self$`min_lat` <- ResponseBoxObject$`min_lat`
      self$`max_lat` <- ResponseBoxObject$`max_lat`
      self$`min_lng` <- ResponseBoxObject$`min_lng`
      self$`max_lng` <- ResponseBoxObject$`max_lng`
      self
    }
  )
)
