# TravelTime API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.2.3
# Contact: support@igeolise.com
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ResponseTimeFilterPostcode
#'
#' @description ResponseTimeFilterPostcode Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field code  character 
#'
#' @field properties  list( \link{ResponseTimeFilterPostcodesProperties} ) 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ResponseTimeFilterPostcode <- R6::R6Class(
  'ResponseTimeFilterPostcode',
  public = list(
    `code` = NULL,
    `properties` = NULL,
    initialize = function(
        `code`, `properties`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`properties`)) {
        stopifnot(is.vector(`properties`), length(`properties`) != 0)
        sapply(`properties`, function(x) stopifnot(R6::is.R6(x)))
        self$`properties` <- `properties`
      }
    },
    toJSON = function() {
      ResponseTimeFilterPostcodeObject <- list()
      if (!is.null(self$`code`)) {
        ResponseTimeFilterPostcodeObject[['code']] <-
          self$`code`
      }
      if (!is.null(self$`properties`)) {
        ResponseTimeFilterPostcodeObject[['properties']] <-
          lapply(self$`properties`, function(x) x$toJSON())
      }

      ResponseTimeFilterPostcodeObject
    },
    fromJSON = function(ResponseTimeFilterPostcodeJson) {
      ResponseTimeFilterPostcodeObject <- jsonlite::fromJSON(ResponseTimeFilterPostcodeJson)
      if (!is.null(ResponseTimeFilterPostcodeObject$`code`)) {
        self$`code` <- ResponseTimeFilterPostcodeObject$`code`
      }
      if (!is.null(ResponseTimeFilterPostcodeObject$`properties`)) {
        self$`properties` <- ApiClient$new()$deserializeObj(ResponseTimeFilterPostcodeObject$`properties`, "array[ResponseTimeFilterPostcodesProperties]", loadNamespace("openapi"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`code`)) {
        sprintf(
        '"code":
          "%s"
                ',
        self$`code`
        )},
        if (!is.null(self$`properties`)) {
        sprintf(
        '"properties":
        [%s]
',
        paste(sapply(self$`properties`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ResponseTimeFilterPostcodeJson) {
      ResponseTimeFilterPostcodeObject <- jsonlite::fromJSON(ResponseTimeFilterPostcodeJson)
      self$`code` <- ResponseTimeFilterPostcodeObject$`code`
      self$`properties` <- ApiClient$new()$deserializeObj(ResponseTimeFilterPostcodeObject$`properties`, "array[ResponseTimeFilterPostcodesProperties]", loadNamespace("openapi"))
      self
    }
  )
)
