# TravelTime Platform API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Contact: support@igeolise.com
# Generated by: https://openapi-generator.tech


#' ResponseBoundingBox Class
#'
#' @field envelope 
#' @field boxes 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ResponseBoundingBox <- R6::R6Class(
  'ResponseBoundingBox',
  public = list(
    `envelope` = NULL,
    `boxes` = NULL,
    initialize = function(`envelope`, `boxes`, ...){
      local.optional.var <- list(...)
      if (!missing(`envelope`)) {
        stopifnot(R6::is.R6(`envelope`))
        self$`envelope` <- `envelope`
      }
      if (!missing(`boxes`)) {
        stopifnot(is.vector(`boxes`), length(`boxes`) != 0)
        sapply(`boxes`, function(x) stopifnot(R6::is.R6(x)))
        self$`boxes` <- `boxes`
      }
    },
    toJSON = function() {
      ResponseBoundingBoxObject <- list()
      if (!is.null(self$`envelope`)) {
        ResponseBoundingBoxObject[['envelope']] <-
          self$`envelope`$toJSON()
      }
      if (!is.null(self$`boxes`)) {
        ResponseBoundingBoxObject[['boxes']] <-
          sapply(self$`boxes`, function(x) x$toJSON())
      }

      ResponseBoundingBoxObject
    },
    fromJSON = function(ResponseBoundingBoxJson) {
      ResponseBoundingBoxObject <- jsonlite::fromJSON(ResponseBoundingBoxJson)
      if (!is.null(ResponseBoundingBoxObject$`envelope`)) {
        envelopeObject <- ResponseBox$new()
        envelopeObject$fromJSON(jsonlite::toJSON(ResponseBoundingBoxObject$envelope, auto_unbox = TRUE))
        self$`envelope` <- envelopeObject
      }
      if (!is.null(ResponseBoundingBoxObject$`boxes`)) {
        self$`boxes` <- sapply(ResponseBoundingBoxObject$`boxes`, function(x) {
          boxesObject <- ResponseBox$new()
          boxesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          boxesObject
        })
      }
    },
    toJSONString = function() {
      sprintf(
        '{
           "envelope":
             %s,
           "boxes":
             [%s]
        }',
        jsonlite::toJSON(self$`envelope`$toJSON(), auto_unbox=TRUE),
        paste(unlist(lapply(self$`boxes`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE))), collapse=",")
      )
    },
    fromJSONString = function(ResponseBoundingBoxJson) {
      ResponseBoundingBoxObject <- jsonlite::fromJSON(ResponseBoundingBoxJson)
      self$`envelope` <- ResponseBox$new()$fromJSON(jsonlite::toJSON(ResponseBoundingBoxObject$envelope, auto_unbox = TRUE))
      data.frame <- ResponseBoundingBoxObject$`boxes`
      self$`boxes` <- vector("list", length = nrow(data.frame))
      for (row in 1:nrow(data.frame)) {
          boxes.node <- ResponseBox$new()
          boxes.node$fromJSON(jsonlite::toJSON(data.frame[row,,drop = TRUE], auto_unbox = TRUE))
          self$`boxes`[[row]] <- boxes.node
      }
      self
    }
  )
)
