//
// RequestRoutesArrivalSearch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct RequestRoutesArrivalSearch: Codable {

    public var _id: String
    public var departureLocationIds: [String]
    public var arrivalLocationId: String
    public var transportation: RequestTransportation
    public var arrivalTime: Date
    public var properties: [RequestRoutesProperty]
    public var range: RequestRangeFull?

    public init(_id: String, departureLocationIds: [String], arrivalLocationId: String, transportation: RequestTransportation, arrivalTime: Date, properties: [RequestRoutesProperty], range: RequestRangeFull?) {
        self._id = _id
        self.departureLocationIds = departureLocationIds
        self.arrivalLocationId = arrivalLocationId
        self.transportation = transportation
        self.arrivalTime = arrivalTime
        self.properties = properties
        self.range = range
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case departureLocationIds = "departure_location_ids"
        case arrivalLocationId = "arrival_location_id"
        case transportation
        case arrivalTime = "arrival_time"
        case properties
        case range
    }


}

