//
// ResponseTimeMapWktResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ResponseTimeMapWktResult: Codable { 


    public var searchId: String
    public var shape: String
    public var properties: ResponseTimeMapProperties

    public init(searchId: String, shape: String, properties: ResponseTimeMapProperties) {
        self.searchId = searchId
        self.shape = shape
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey { 
        case searchId = "search_id"
        case shape
        case properties
    }

}
