//
// ResponseFareTicket.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ResponseFareTicket: Codable {

    public enum ModelType: String, Codable {
        case single = "single"
        case week = "week"
        case month = "month"
        case year = "year"
    }
    public var type: ModelType
    public var price: Double
    public var currency: String

    public init(type: ModelType, price: Double, currency: String) {
        self.type = type
        self.price = price
        self.currency = currency
    }


}

