# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ResponseGeocoding")

model.instance <- ResponseGeocoding$new()

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("features", {
  # tests for the property `features` (array[ResponseGeocodingGeoJsonFeature])

  # uncomment below to test the property 
  #expect_equal(model.instance$`features`, "EXPECTED_RESULT")
})

