# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RequestTimeMapDepartureSearch")

model.instance <- RequestTimeMapDepartureSearch$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("coords", {
  # tests for the property `coords` (Coords)

  # uncomment below to test the property 
  #expect_equal(model.instance$`coords`, "EXPECTED_RESULT")
})

test_that("transportation", {
  # tests for the property `transportation` (RequestTransportation)

  # uncomment below to test the property 
  #expect_equal(model.instance$`transportation`, "EXPECTED_RESULT")
})

test_that("travel_time", {
  # tests for the property `travel_time` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`travel_time`, "EXPECTED_RESULT")
})

test_that("departure_time", {
  # tests for the property `departure_time` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`departure_time`, "EXPECTED_RESULT")
})

test_that("properties", {
  # tests for the property `properties` (array[RequestTimeMapProperty])

  # uncomment below to test the property 
  #expect_equal(model.instance$`properties`, "EXPECTED_RESULT")
})

test_that("range", {
  # tests for the property `range` (RequestRangeNoMaxResults)

  # uncomment below to test the property 
  #expect_equal(model.instance$`range`, "EXPECTED_RESULT")
})

test_that("level_of_detail", {
  # tests for the property `level_of_detail` (RequestLevelOfDetail)

  # uncomment below to test the property 
  #expect_equal(model.instance$`level_of_detail`, "EXPECTED_RESULT")
})

