# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api.instance <- DefaultApi$new()

test_that("GeocodingReverseSearch", {
  # tests for GeocodingReverseSearch
  # base path: https://api.traveltimeapp.com
  # @param numeric  lat   
  # @param numeric  lng   
  # @param character  within.country    (optional)
  # @return [ResponseGeocoding]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GeocodingSearch", {
  # tests for GeocodingSearch
  # base path: https://api.traveltimeapp.com
  # @param character  query   
  # @param numeric  focus.lat    (optional)
  # @param numeric  focus.lng    (optional)
  # @param character  within.country    (optional)
  # @return [ResponseGeocoding]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MapInfo", {
  # tests for MapInfo
  # base path: https://api.traveltimeapp.com
  # @return [ResponseMapInfo]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Routes", {
  # tests for Routes
  # base path: https://api.traveltimeapp.com
  # @param RequestRoutes  request.routes   
  # @return [ResponseRoutes]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SupportedLocations", {
  # tests for SupportedLocations
  # base path: https://api.traveltimeapp.com
  # @param RequestSupportedLocations  request.supported.locations   
  # @return [ResponseSupportedLocations]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TimeFilter", {
  # tests for TimeFilter
  # base path: https://api.traveltimeapp.com
  # @param RequestTimeFilter  request.time.filter   
  # @return [ResponseTimeFilter]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TimeFilterFast", {
  # tests for TimeFilterFast
  # base path: https://api.traveltimeapp.com
  # @param RequestTimeFilterFast  request.time.filter.fast   
  # @return [ResponseTimeFilterFast]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TimeFilterPostcodeDistricts", {
  # tests for TimeFilterPostcodeDistricts
  # base path: https://api.traveltimeapp.com
  # @param RequestTimeFilterPostcodeDistricts  request.time.filter.postcode.districts   
  # @return [ResponseTimeFilterPostcodeDistricts]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TimeFilterPostcodeSectors", {
  # tests for TimeFilterPostcodeSectors
  # base path: https://api.traveltimeapp.com
  # @param RequestTimeFilterPostcodeSectors  request.time.filter.postcode.sectors   
  # @return [ResponseTimeFilterPostcodeSectors]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TimeFilterPostcodes", {
  # tests for TimeFilterPostcodes
  # base path: https://api.traveltimeapp.com
  # @param RequestTimeFilterPostcodes  request.time.filter.postcodes   
  # @return [ResponseTimeFilterPostcodes]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TimeMap", {
  # tests for TimeMap
  # base path: https://api.traveltimeapp.com
  # @param RequestTimeMap  request.time.map   
  # @return [ResponseTimeMap]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

