/**
 * TravelTime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "RequestRoutesArrivalSearch.h"

#include <string>
#include <sstream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

RequestRoutesArrivalSearch::RequestRoutesArrivalSearch()
{
	m_Id = "";
	m_Arrival_location_id = "";
	m_Arrival_time = "";
}

RequestRoutesArrivalSearch::~RequestRoutesArrivalSearch()
{
}

std::string RequestRoutesArrivalSearch::toJsonString(bool prettyJson)
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
	return ss.str();
}

void RequestRoutesArrivalSearch::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree RequestRoutesArrivalSearch::toPropertyTree()
{
	ptree pt;
	ptree tmp_node;
	pt.put("id", m_Id);
	// generate tree for Departure_location_ids
	if (!m_Departure_location_ids.empty()) {
		for (const auto &childEntry : m_Departure_location_ids) {
			ptree Departure_location_ids_node;
			Departure_location_ids_node.put("", childEntry);
			tmp_node.push_back(std::make_pair("", Departure_location_ids_node));
		}
		pt.add_child("departure_location_ids", tmp_node);
		tmp_node.clear();
	}
	pt.put("arrival_location_id", m_Arrival_location_id);
	if (m_Transportation != nullptr) {
		pt.add_child("transportation", m_Transportation->toPropertyTree());
	}
	pt.put("arrival_time", m_Arrival_time);
	// generate tree for Properties
	if (!m_Properties.empty()) {
		for (const auto &childEntry : m_Properties) {
			ptree Properties_node;
			Properties_node.put("", childEntry);
			tmp_node.push_back(std::make_pair("", Properties_node));
		}
		pt.add_child("properties", tmp_node);
		tmp_node.clear();
	}
	if (m_Range != nullptr) {
		pt.add_child("range", m_Range->toPropertyTree());
	}
	return pt;
}

void RequestRoutesArrivalSearch::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	m_Id = pt.get("id", "");
	// push all items of Departure_location_ids into member vector
	if (pt.get_child_optional("departure_location_ids")) {
		for (const auto &childTree : pt.get_child("departure_location_ids")) {
			m_Departure_location_ids.emplace_back(childTree.second.data());
		}
	}
	m_Arrival_location_id = pt.get("arrival_location_id", "");
	if (pt.get_child_optional("transportation")) {
		m_Transportation = std::make_shared<RequestTransportation>();
		m_Transportation->fromPropertyTree(pt.get_child("transportation"));
	}
	m_Arrival_time = pt.get("arrival_time", "");
	// push all items of Properties into member vector
	if (pt.get_child_optional("properties")) {
		for (const auto &childTree : pt.get_child("properties")) {
			m_Properties.emplace_back(childTree.second.data());
		}
	}
	if (pt.get_child_optional("range")) {
		m_Range = std::make_shared<RequestRangeFull>();
		m_Range->fromPropertyTree(pt.get_child("range"));
	}
}

std::string RequestRoutesArrivalSearch::getId() const
{
    return m_Id;
}
void RequestRoutesArrivalSearch::setId(std::string value)
{
	m_Id = value;
}
std::vector<std::string> RequestRoutesArrivalSearch::getDepartureLocationIds() const
{
    return m_Departure_location_ids;
}
void RequestRoutesArrivalSearch::setDepartureLocationIds(std::vector<std::string> value)
{
	m_Departure_location_ids = value;
}
std::string RequestRoutesArrivalSearch::getArrivalLocationId() const
{
    return m_Arrival_location_id;
}
void RequestRoutesArrivalSearch::setArrivalLocationId(std::string value)
{
	m_Arrival_location_id = value;
}
std::shared_ptr<RequestTransportation> RequestRoutesArrivalSearch::getTransportation() const
{
    return m_Transportation;
}
void RequestRoutesArrivalSearch::setTransportation(std::shared_ptr<RequestTransportation> value)
{
	m_Transportation = value;
}
std::string RequestRoutesArrivalSearch::getArrivalTime() const
{
    return m_Arrival_time;
}
void RequestRoutesArrivalSearch::setArrivalTime(std::string value)
{
	m_Arrival_time = value;
}
std::vector<std::shared_ptr<RequestRoutesProperty>> RequestRoutesArrivalSearch::getProperties() const
{
    return m_Properties;
}
void RequestRoutesArrivalSearch::setProperties(std::vector<std::shared_ptr<RequestRoutesProperty>> value)
{
	m_Properties = value;
}
std::shared_ptr<RequestRangeFull> RequestRoutesArrivalSearch::getRange() const
{
    return m_Range;
}
void RequestRoutesArrivalSearch::setRange(std::shared_ptr<RequestRangeFull> value)
{
	m_Range = value;
}

}
}
}
}

