/**
 * TravelTime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RequestUnionOnIntersection.h
 *
 * 
 */

#ifndef RequestUnionOnIntersection_H_
#define RequestUnionOnIntersection_H_



#include <string>
#include <vector>
#include <memory>
#include <boost/property_tree/ptree.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  RequestUnionOnIntersection 
{
public:
    RequestUnionOnIntersection();
    virtual ~RequestUnionOnIntersection();
    
    std::string toJsonString(bool prettyJson = false);
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree();
    void fromPropertyTree(boost::property_tree::ptree const& pt);

    /////////////////////////////////////////////
    /// RequestUnionOnIntersection members

    /// <summary>
    /// 
    /// </summary>
    std::string getId() const;
    void setId(std::string value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string> getSearchIds() const;
    void setSearchIds(std::vector<std::string> value);
protected:
    std::string m_Id;
    std::vector<std::string> m_Search_ids;
};

}
}
}
}

#endif /* RequestUnionOnIntersection_H_ */
