/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "RequestTimeFilterPostcodeDistricts.h"

#include <string>
#include <sstream>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

RequestTimeFilterPostcodeDistricts::RequestTimeFilterPostcodeDistricts()
{
    
}

RequestTimeFilterPostcodeDistricts::~RequestTimeFilterPostcodeDistricts()
{
}

std::string RequestTimeFilterPostcodeDistricts::toJsonString()
{
	std::stringstream ss;
	ptree pt;
	write_json(ss, pt, false);
	return ss.str();
}

void RequestTimeFilterPostcodeDistricts::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
}

std::vector<std::shared_ptr<RequestTimeFilterPostcodeDistrictsDepartureSearch>> RequestTimeFilterPostcodeDistricts::getDepartureSearches() const
{
    return m_Departure_searches;
}
void RequestTimeFilterPostcodeDistricts::setDepartureSearches(std::vector<std::shared_ptr<RequestTimeFilterPostcodeDistrictsDepartureSearch>> value)
{
    m_Departure_searches = value;
}
std::vector<std::shared_ptr<RequestTimeFilterPostcodeDistrictsArrivalSearch>> RequestTimeFilterPostcodeDistricts::getArrivalSearches() const
{
    return m_Arrival_searches;
}
void RequestTimeFilterPostcodeDistricts::setArrivalSearches(std::vector<std::shared_ptr<RequestTimeFilterPostcodeDistrictsArrivalSearch>> value)
{
    m_Arrival_searches = value;
}

}
}
}
}

