/**
 * TravelTime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.2.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ResponseTimeFilterResult.h
 *
 * 
 */

#ifndef ResponseTimeFilterResult_H_
#define ResponseTimeFilterResult_H_



#include <string>
#include <vector>
#include "ResponseTimeFilterLocation.h"
#include <memory>
#include <boost/property_tree/ptree.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  ResponseTimeFilterResult 
{
public:
    ResponseTimeFilterResult();
    virtual ~ResponseTimeFilterResult();
    
    std::string toJsonString(bool prettyJson = false);
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree();
    void fromPropertyTree(boost::property_tree::ptree const& pt);

    /////////////////////////////////////////////
    /// ResponseTimeFilterResult members

    /// <summary>
    /// 
    /// </summary>
    std::string getSearchId() const;
    void setSearchId(std::string value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<ResponseTimeFilterLocation>> getLocations() const;
    void setLocations(std::vector<std::shared_ptr<ResponseTimeFilterLocation>> value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::string> getUnreachable() const;
    void setUnreachable(std::vector<std::string> value);
protected:
    std::string m_Search_id;
    std::vector<std::shared_ptr<ResponseTimeFilterLocation>> m_Locations;
    std::vector<std::string> m_Unreachable;
};

}
}
}
}

#endif /* ResponseTimeFilterResult_H_ */
