/**
 * TravelTime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.2.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ResponseTimeFilterPostcodeSector.h"

#include <string>
#include <sstream>
#include <stdexcept>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

ResponseTimeFilterPostcodeSector::ResponseTimeFilterPostcodeSector()
{
	m_Code = "";
}

ResponseTimeFilterPostcodeSector::~ResponseTimeFilterPostcodeSector()
{
}

std::string ResponseTimeFilterPostcodeSector::toJsonString(bool prettyJson)
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
	return ss.str();
}

void ResponseTimeFilterPostcodeSector::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree ResponseTimeFilterPostcodeSector::toPropertyTree()
{
	ptree pt;
	ptree tmp_node;
	pt.put("code", m_Code);
	if (m_Properties != nullptr) {
		pt.add_child("properties", m_Properties->toPropertyTree());
	}
	return pt;
}

void ResponseTimeFilterPostcodeSector::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	m_Code = pt.get("code", "");
	if (pt.get_child_optional("properties")) {
		m_Properties = std::make_shared<ResponseTimeFilterPostcodeSectorProperties>();
		m_Properties->fromPropertyTree(pt.get_child("properties"));
	}
}

std::string ResponseTimeFilterPostcodeSector::getCode() const
{
    return m_Code;
}
void ResponseTimeFilterPostcodeSector::setCode(std::string value)
{
	m_Code = value;
}
std::shared_ptr<ResponseTimeFilterPostcodeSectorProperties> ResponseTimeFilterPostcodeSector::getProperties() const
{
    return m_Properties;
}
void ResponseTimeFilterPostcodeSector::setProperties(std::shared_ptr<ResponseTimeFilterPostcodeSectorProperties> value)
{
	m_Properties = value;
}

}
}
}
}

