/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ResponseTimeFilterFastProperties.h
 *
 * 
 */

#ifndef ResponseTimeFilterFastProperties_H_
#define ResponseTimeFilterFastProperties_H_



#include "ResponseFaresFast.h"
#include <memory>
#include <boost/property_tree/ptree.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  ResponseTimeFilterFastProperties 
{
public:
    ResponseTimeFilterFastProperties();
    virtual ~ResponseTimeFilterFastProperties();
    
    std::string toJsonString(bool prettyJson = false);
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree();
    void fromPropertyTree(boost::property_tree::ptree const& pt);

    /////////////////////////////////////////////
    /// ResponseTimeFilterFastProperties members

    /// <summary>
    /// 
    /// </summary>
    int32_t getTravelTime() const;
    void setTravelTime(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ResponseFaresFast> getFares() const;
    void setFares(std::shared_ptr<ResponseFaresFast> value);
protected:
    int32_t m_Travel_time;
    std::shared_ptr<ResponseFaresFast> m_Fares;
};

}
}
}
}

#endif /* ResponseTimeFilterFastProperties_H_ */
