/**
 * TravelTime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.2.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "ResponseRoute.h"

#include <string>
#include <sstream>
#include <stdexcept>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

ResponseRoute::ResponseRoute()
{
	m_Departure_time = "";
	m_Arrival_time = "";
}

ResponseRoute::~ResponseRoute()
{
}

std::string ResponseRoute::toJsonString(bool prettyJson)
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
	return ss.str();
}

void ResponseRoute::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree ResponseRoute::toPropertyTree()
{
	ptree pt;
	ptree tmp_node;
	pt.put("departure_time", m_Departure_time);
	pt.put("arrival_time", m_Arrival_time);
	// generate tree for Parts
	if (!m_Parts.empty()) {
		for (const auto &childEntry : m_Parts) {
			ptree Parts_node;
			Parts_node.put("", childEntry);
			tmp_node.push_back(std::make_pair("", Parts_node));
		}
		pt.add_child("parts", tmp_node);
		tmp_node.clear();
	}
	return pt;
}

void ResponseRoute::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	m_Departure_time = pt.get("departure_time", "");
	m_Arrival_time = pt.get("arrival_time", "");
	// push all items of Parts into member vector
	if (pt.get_child_optional("parts")) {
		for (const auto &childTree : pt.get_child("parts")) {
			m_Parts.emplace_back(childTree.second.data());
		}
	}
}

std::string ResponseRoute::getDepartureTime() const
{
    return m_Departure_time;
}
void ResponseRoute::setDepartureTime(std::string value)
{
	m_Departure_time = value;
}
std::string ResponseRoute::getArrivalTime() const
{
    return m_Arrival_time;
}
void ResponseRoute::setArrivalTime(std::string value)
{
	m_Arrival_time = value;
}
std::vector<std::shared_ptr<ResponseRoutePart>> ResponseRoute::getParts() const
{
    return m_Parts;
}
void ResponseRoute::setParts(std::vector<std::shared_ptr<ResponseRoutePart>> value)
{
	m_Parts = value;
}

}
}
}
}

