/**
 * TravelTime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.2.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ResponseTimeMapWktResult.h
 *
 * 
 */

#ifndef ResponseTimeMapWktResult_H_
#define ResponseTimeMapWktResult_H_



#include <string>
#include "ResponseTimeMapProperties.h"
#include <memory>
#include <boost/property_tree/ptree.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  ResponseTimeMapWktResult 
{
public:
    ResponseTimeMapWktResult();
    virtual ~ResponseTimeMapWktResult();
    
    std::string toJsonString(bool prettyJson = false);
    void fromJsonString(std::string const& jsonString);
    boost::property_tree::ptree toPropertyTree();
    void fromPropertyTree(boost::property_tree::ptree const& pt);

    /////////////////////////////////////////////
    /// ResponseTimeMapWktResult members

    /// <summary>
    /// 
    /// </summary>
    std::string getSearchId() const;
    void setSearchId(std::string value);

    /// <summary>
    /// 
    /// </summary>
    std::string getShape() const;
    void setShape(std::string value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<ResponseTimeMapProperties> getProperties() const;
    void setProperties(std::shared_ptr<ResponseTimeMapProperties> value);
protected:
    std::string m_Search_id;
    std::string m_Shape;
    std::shared_ptr<ResponseTimeMapProperties> m_Properties;
};

}
}
}
}

#endif /* ResponseTimeMapWktResult_H_ */
