/**
 * TravelTime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RequestArrivalTimePeriod from './RequestArrivalTimePeriod';
import RequestTimeFilterFastProperty from './RequestTimeFilterFastProperty';
import RequestTransportationFast from './RequestTransportationFast';

/**
 * The RequestTimeFilterFastArrivalOneToManySearch model module.
 * @module model/RequestTimeFilterFastArrivalOneToManySearch
 * @version 1.2.3
 */
class RequestTimeFilterFastArrivalOneToManySearch {
    /**
     * Constructs a new <code>RequestTimeFilterFastArrivalOneToManySearch</code>.
     * @alias module:model/RequestTimeFilterFastArrivalOneToManySearch
     * @param id {String} 
     * @param departureLocationId {String} 
     * @param arrivalLocationIds {Array.<String>} 
     * @param transportation {module:model/RequestTransportationFast} 
     * @param travelTime {Number} 
     * @param arrivalTimePeriod {module:model/RequestArrivalTimePeriod} 
     * @param properties {Array.<module:model/RequestTimeFilterFastProperty>} 
     */
    constructor(id, departureLocationId, arrivalLocationIds, transportation, travelTime, arrivalTimePeriod, properties) { 
        
        RequestTimeFilterFastArrivalOneToManySearch.initialize(this, id, departureLocationId, arrivalLocationIds, transportation, travelTime, arrivalTimePeriod, properties);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, departureLocationId, arrivalLocationIds, transportation, travelTime, arrivalTimePeriod, properties) { 
        obj['id'] = id;
        obj['departure_location_id'] = departureLocationId;
        obj['arrival_location_ids'] = arrivalLocationIds;
        obj['transportation'] = transportation;
        obj['travel_time'] = travelTime;
        obj['arrival_time_period'] = arrivalTimePeriod;
        obj['properties'] = properties;
    }

    /**
     * Constructs a <code>RequestTimeFilterFastArrivalOneToManySearch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestTimeFilterFastArrivalOneToManySearch} obj Optional instance to populate.
     * @return {module:model/RequestTimeFilterFastArrivalOneToManySearch} The populated <code>RequestTimeFilterFastArrivalOneToManySearch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestTimeFilterFastArrivalOneToManySearch();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('departure_location_id')) {
                obj['departure_location_id'] = ApiClient.convertToType(data['departure_location_id'], 'String');
            }
            if (data.hasOwnProperty('arrival_location_ids')) {
                obj['arrival_location_ids'] = ApiClient.convertToType(data['arrival_location_ids'], ['String']);
            }
            if (data.hasOwnProperty('transportation')) {
                obj['transportation'] = RequestTransportationFast.constructFromObject(data['transportation']);
            }
            if (data.hasOwnProperty('travel_time')) {
                obj['travel_time'] = ApiClient.convertToType(data['travel_time'], 'Number');
            }
            if (data.hasOwnProperty('arrival_time_period')) {
                obj['arrival_time_period'] = RequestArrivalTimePeriod.constructFromObject(data['arrival_time_period']);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [RequestTimeFilterFastProperty]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
RequestTimeFilterFastArrivalOneToManySearch.prototype['id'] = undefined;

/**
 * @member {String} departure_location_id
 */
RequestTimeFilterFastArrivalOneToManySearch.prototype['departure_location_id'] = undefined;

/**
 * @member {Array.<String>} arrival_location_ids
 */
RequestTimeFilterFastArrivalOneToManySearch.prototype['arrival_location_ids'] = undefined;

/**
 * @member {module:model/RequestTransportationFast} transportation
 */
RequestTimeFilterFastArrivalOneToManySearch.prototype['transportation'] = undefined;

/**
 * @member {Number} travel_time
 */
RequestTimeFilterFastArrivalOneToManySearch.prototype['travel_time'] = undefined;

/**
 * @member {module:model/RequestArrivalTimePeriod} arrival_time_period
 */
RequestTimeFilterFastArrivalOneToManySearch.prototype['arrival_time_period'] = undefined;

/**
 * @member {Array.<module:model/RequestTimeFilterFastProperty>} properties
 */
RequestTimeFilterFastArrivalOneToManySearch.prototype['properties'] = undefined;






export default RequestTimeFilterFastArrivalOneToManySearch;

