/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TravelTimePlatformApi) {
      root.TravelTimePlatformApi = {};
    }
    root.TravelTimePlatformApi.RequestTransportationFast = factory(root.TravelTimePlatformApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The RequestTransportationFast model module.
   * @module model/RequestTransportationFast
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RequestTransportationFast</code>.
   * @alias module:model/RequestTransportationFast
   * @class
   * @param type {module:model/RequestTransportationFast.TypeEnum} 
   */
  var exports = function(type) {
    var _this = this;

    _this['type'] = type;
  };

  /**
   * Constructs a <code>RequestTransportationFast</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestTransportationFast} obj Optional instance to populate.
   * @return {module:model/RequestTransportationFast} The populated <code>RequestTransportationFast</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/RequestTransportationFast.TypeEnum} type
   */
  exports.prototype['type'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "public_transport"
     * @const
     */
    "public_transport": "public_transport",
    /**
     * value: "driving"
     * @const
     */
    "driving": "driving",
    /**
     * value: "driving+public_transport"
     * @const
     */
    "driving+public_transport": "driving+public_transport"  };


  return exports;
}));


