/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TravelTimePlatformApi) {
      root.TravelTimePlatformApi = {};
    }
    root.TravelTimePlatformApi.RequestTimeFilterPostcodeDistrictsProperty = factory(root.TravelTimePlatformApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class RequestTimeFilterPostcodeDistrictsProperty.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "travel_time_reachable"
     * @const
     */
    "travel_time_reachable": "travel_time_reachable",
    /**
     * value: "travel_time_all"
     * @const
     */
    "travel_time_all": "travel_time_all",
    /**
     * value: "coverage"
     * @const
     */
    "coverage": "coverage"  };

  /**
   * Returns a <code>RequestTimeFilterPostcodeDistrictsProperty</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/RequestTimeFilterPostcodeDistrictsProperty} The enum <code>RequestTimeFilterPostcodeDistrictsProperty</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


