/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TravelTimePlatformApi) {
      root.TravelTimePlatformApi = {};
    }
    root.TravelTimePlatformApi.ResponseError = factory(root.TravelTimePlatformApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ResponseError model module.
   * @module model/ResponseError
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ResponseError</code>.
   * @alias module:model/ResponseError
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>ResponseError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponseError} obj Optional instance to populate.
   * @return {module:model/ResponseError} The populated <code>ResponseError</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('http_status')) {
        obj['http_status'] = ApiClient.convertToType(data['http_status'], 'Number');
      }
      if (data.hasOwnProperty('error_code')) {
        obj['error_code'] = ApiClient.convertToType(data['error_code'], 'Number');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('documentation_link')) {
        obj['documentation_link'] = ApiClient.convertToType(data['documentation_link'], 'String');
      }
      if (data.hasOwnProperty('additional_info')) {
        obj['additional_info'] = ApiClient.convertToType(data['additional_info'], {'String': ['String']});
      }
    }
    return obj;
  }

  /**
   * @member {Number} http_status
   */
  exports.prototype['http_status'] = undefined;
  /**
   * @member {Number} error_code
   */
  exports.prototype['error_code'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} documentation_link
   */
  exports.prototype['documentation_link'] = undefined;
  /**
   * @member {Object.<String, Array.<String>>} additional_info
   */
  exports.prototype['additional_info'] = undefined;



  return exports;
}));


