/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ResponseTimeFilterResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ResponseTimeFilterResult'));
  } else {
    // Browser globals (root is window)
    if (!root.TravelTimePlatformApi) {
      root.TravelTimePlatformApi = {};
    }
    root.TravelTimePlatformApi.ResponseTimeFilter = factory(root.TravelTimePlatformApi.ApiClient, root.TravelTimePlatformApi.ResponseTimeFilterResult);
  }
}(this, function(ApiClient, ResponseTimeFilterResult) {
  'use strict';



  /**
   * The ResponseTimeFilter model module.
   * @module model/ResponseTimeFilter
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ResponseTimeFilter</code>.
   * @alias module:model/ResponseTimeFilter
   * @class
   * @param results {Array.<module:model/ResponseTimeFilterResult>} 
   */
  var exports = function(results) {
    var _this = this;

    _this['results'] = results;
  };

  /**
   * Constructs a <code>ResponseTimeFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponseTimeFilter} obj Optional instance to populate.
   * @return {module:model/ResponseTimeFilter} The populated <code>ResponseTimeFilter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('results')) {
        obj['results'] = ApiClient.convertToType(data['results'], [ResponseTimeFilterResult]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ResponseTimeFilterResult>} results
   */
  exports.prototype['results'] = undefined;



  return exports;
}));


