/* 
 * TravelTime Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using traveltimeplatform.Api;
using traveltimeplatform.Model;
using traveltimeplatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace traveltimeplatform.Test
{
    /// <summary>
    ///  Class for testing RequestArrivalTimePeriod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RequestArrivalTimePeriodTests
    {
        // TODO uncomment below to declare an instance variable for RequestArrivalTimePeriod
        //private RequestArrivalTimePeriod instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RequestArrivalTimePeriod
            //instance = new RequestArrivalTimePeriod();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RequestArrivalTimePeriod
        /// </summary>
        [Test]
        public void RequestArrivalTimePeriodInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RequestArrivalTimePeriod
            //Assert.IsInstanceOfType<RequestArrivalTimePeriod> (instance, "variable 'instance' is a RequestArrivalTimePeriod");
        }



    }

}
