/* 
 * TravelTime Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using traveltimeplatform.Api;
using traveltimeplatform.Model;
using traveltimeplatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace traveltimeplatform.Test
{
    /// <summary>
    ///  Class for testing ResponseTimeFilterPostcode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseTimeFilterPostcodeTests
    {
        // TODO uncomment below to declare an instance variable for ResponseTimeFilterPostcode
        //private ResponseTimeFilterPostcode instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseTimeFilterPostcode
            //instance = new ResponseTimeFilterPostcode();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseTimeFilterPostcode
        /// </summary>
        [Test]
        public void ResponseTimeFilterPostcodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseTimeFilterPostcode
            //Assert.IsInstanceOfType<ResponseTimeFilterPostcode> (instance, "variable 'instance' is a ResponseTimeFilterPostcode");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

    }

}
