/* 
 * TravelTime Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@igeolise.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using traveltimeplatform.Api;
using traveltimeplatform.Model;
using traveltimeplatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace traveltimeplatform.Test
{
    /// <summary>
    ///  Class for testing ResponseTimeFilterResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseTimeFilterResultTests
    {
        // TODO uncomment below to declare an instance variable for ResponseTimeFilterResult
        //private ResponseTimeFilterResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseTimeFilterResult
            //instance = new ResponseTimeFilterResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseTimeFilterResult
        /// </summary>
        [Test]
        public void ResponseTimeFilterResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseTimeFilterResult
            //Assert.IsInstanceOfType<ResponseTimeFilterResult> (instance, "variable 'instance' is a ResponseTimeFilterResult");
        }


        /// <summary>
        /// Test the property 'SearchId'
        /// </summary>
        [Test]
        public void SearchIdTest()
        {
            // TODO unit test for the property 'SearchId'
        }
        /// <summary>
        /// Test the property 'Locations'
        /// </summary>
        [Test]
        public void LocationsTest()
        {
            // TODO unit test for the property 'Locations'
        }
        /// <summary>
        /// Test the property 'Unreachable'
        /// </summary>
        [Test]
        public void UnreachableTest()
        {
            // TODO unit test for the property 'Unreachable'
        }

    }

}
