# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from traveltimeplatform.models.base_model_ import Model
from traveltimeplatform.models.response_time_filter_result import ResponseTimeFilterResult
from traveltimeplatform import util


class ResponseTimeFilter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, results: List[ResponseTimeFilterResult]=None):
        """ResponseTimeFilter - a model defined in OpenAPI

        :param results: The results of this ResponseTimeFilter.
        """
        self.openapi_types = {
            'results': List[ResponseTimeFilterResult]
        }

        self.attribute_map = {
            'results': 'results'
        }

        self._results = results

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ResponseTimeFilter':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ResponseTimeFilter of this ResponseTimeFilter.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def results(self):
        """Gets the results of this ResponseTimeFilter.


        :return: The results of this ResponseTimeFilter.
        :rtype: List[ResponseTimeFilterResult]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this ResponseTimeFilter.


        :param results: The results of this ResponseTimeFilter.
        :type results: List[ResponseTimeFilterResult]
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")

        self._results = results
