/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ResponseGeocodingProperties {
    "name": string;
    "label": string;
    "score"?: number;
    "houseNumber"?: string;
    "street"?: string;
    "region"?: string;
    "regionCode"?: string;
    "neighbourhood"?: string;
    "county"?: string;
    "macroregion"?: string;
    "city"?: string;
    "country"?: string;
    "countryCode"?: string;
    "continent"?: string;
    "postcode"?: string;
    "features"?: models.ResponseMapInfoFeatures;
}

