/* 
 * TravelTime Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using traveltimeplatform.Api;
using traveltimeplatform.Model;
using traveltimeplatform.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace traveltimeplatform.Test
{
    /// <summary>
    ///  Class for testing ResponseFares
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResponseFaresTests
    {
        // TODO uncomment below to declare an instance variable for ResponseFares
        //private ResponseFares instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResponseFares
            //instance = new ResponseFares();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResponseFares
        /// </summary>
        [Test]
        public void ResponseFaresInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseFares
            //Assert.IsInstanceOfType<ResponseFares> (instance, "variable 'instance' is a ResponseFares");
        }


        /// <summary>
        /// Test the property 'Breakdown'
        /// </summary>
        [Test]
        public void BreakdownTest()
        {
            // TODO unit test for the property 'Breakdown'
        }
        /// <summary>
        /// Test the property 'TicketsTotal'
        /// </summary>
        [Test]
        public void TicketsTotalTest()
        {
            // TODO unit test for the property 'TicketsTotal'
        }

    }

}
