//
// RequestTransportation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public class RequestTransportation: JSONEncodable {
    public enum ModelType: String { 
        case Cycling = "cycling"
        case Driving = "driving"
        case Driving+train = "driving+train"
        case PublicTransport = "public_transport"
        case Walking = "walking"
        case Coach = "coach"
        case Bus = "bus"
        case Train = "train"
        case Ferry = "ferry"
        case Driving+ferry = "driving+ferry"
        case Cycling+ferry = "cycling+ferry"
    }
    public var type: ModelType?
    public var ptChangeDelay: Int32?
    public var walkingTime: Int32?
    public var drivingTimeToStation: Int32?
    public var parkingTime: Int32?
    public var boardingTime: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["type"] = self.type?.rawValue
        nillableDictionary["pt_change_delay"] = self.ptChangeDelay?.encodeToJSON()
        nillableDictionary["walking_time"] = self.walkingTime?.encodeToJSON()
        nillableDictionary["driving_time_to_station"] = self.drivingTimeToStation?.encodeToJSON()
        nillableDictionary["parking_time"] = self.parkingTime?.encodeToJSON()
        nillableDictionary["boarding_time"] = self.boardingTime?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
