//
// RequestUnionOnIntersection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public class RequestUnionOnIntersection: JSONEncodable {
    public var id: String?
    public var searchIds: [String]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["search_ids"] = self.searchIds?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
