//
// ResponseDistanceBreakdownItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public class ResponseDistanceBreakdownItem: JSONEncodable {
    public var mode: ResponseTransportationMode?
    public var distance: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["mode"] = self.mode?.encodeToJSON()
        nillableDictionary["distance"] = self.distance?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
