//
// ResponseRoute.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public class ResponseRoute: JSONEncodable {
    public var departureTime: NSDate?
    public var arrivalTime: NSDate?
    public var parts: [ResponseRoutePart]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["departure_time"] = self.departureTime?.encodeToJSON()
        nillableDictionary["arrival_time"] = self.arrivalTime?.encodeToJSON()
        nillableDictionary["parts"] = self.parts?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
