/* tslint:disable */
/* eslint-disable */
/**
 * TravelTime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ResponseTimeFilterPostcodeSectorProperties,
    ResponseTimeFilterPostcodeSectorPropertiesFromJSON,
    ResponseTimeFilterPostcodeSectorPropertiesFromJSONTyped,
    ResponseTimeFilterPostcodeSectorPropertiesToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResponseTimeFilterPostcodeSector
 */
export interface ResponseTimeFilterPostcodeSector {
    /**
     * 
     * @type {string}
     * @memberof ResponseTimeFilterPostcodeSector
     */
    code: string;
    /**
     * 
     * @type {ResponseTimeFilterPostcodeSectorProperties}
     * @memberof ResponseTimeFilterPostcodeSector
     */
    properties: ResponseTimeFilterPostcodeSectorProperties;
}

export function ResponseTimeFilterPostcodeSectorFromJSON(json: any): ResponseTimeFilterPostcodeSector {
    return ResponseTimeFilterPostcodeSectorFromJSONTyped(json, false);
}

export function ResponseTimeFilterPostcodeSectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseTimeFilterPostcodeSector {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'properties': ResponseTimeFilterPostcodeSectorPropertiesFromJSON(json['properties']),
    };
}

export function ResponseTimeFilterPostcodeSectorToJSON(value?: ResponseTimeFilterPostcodeSector | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'properties': ResponseTimeFilterPostcodeSectorPropertiesToJSON(value.properties),
    };
}


