// tslint:disable
/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    ResponseRoutesResult,
    ResponseRoutesResultFromJSON,
    ResponseRoutesResultToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResponseRoutes
 */
export interface ResponseRoutes {
    /**
     * 
     * @type {Array<ResponseRoutesResult>}
     * @memberof ResponseRoutes
     */
    results: Array<ResponseRoutesResult>;
}

export function ResponseRoutesFromJSON(json: any): ResponseRoutes {
    return {
        'results': (json['results'] as Array<any>).map(ResponseRoutesResultFromJSON),
    };
}

export function ResponseRoutesToJSON(value?: ResponseRoutes): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'results': (value.results as Array<any>).map(ResponseRoutesResultToJSON),
    };
}


