/* tslint:disable */
/* eslint-disable */
/**
 * TravelTime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ResponseTimeMapProperties,
    ResponseTimeMapPropertiesFromJSON,
    ResponseTimeMapPropertiesFromJSONTyped,
    ResponseTimeMapPropertiesToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResponseTimeMapWktResult
 */
export interface ResponseTimeMapWktResult {
    /**
     * 
     * @type {string}
     * @memberof ResponseTimeMapWktResult
     */
    searchId: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseTimeMapWktResult
     */
    shape: string;
    /**
     * 
     * @type {ResponseTimeMapProperties}
     * @memberof ResponseTimeMapWktResult
     */
    properties: ResponseTimeMapProperties;
}

export function ResponseTimeMapWktResultFromJSON(json: any): ResponseTimeMapWktResult {
    return ResponseTimeMapWktResultFromJSONTyped(json, false);
}

export function ResponseTimeMapWktResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseTimeMapWktResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'searchId': json['search_id'],
        'shape': json['shape'],
        'properties': ResponseTimeMapPropertiesFromJSON(json['properties']),
    };
}

export function ResponseTimeMapWktResultToJSON(value?: ResponseTimeMapWktResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'search_id': value.searchId,
        'shape': value.shape,
        'properties': ResponseTimeMapPropertiesToJSON(value.properties),
    };
}


