<?php
/**
 * RequestTimeFilterArrivalSearchTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * TravelTime Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@igeolise.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

/**
 * RequestTimeFilterArrivalSearchTest Class Doc Comment
 *
 * @category    Class */
// * @description RequestTimeFilterArrivalSearch
/**
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class RequestTimeFilterArrivalSearchTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RequestTimeFilterArrivalSearch"
     */
    public function testRequestTimeFilterArrivalSearch()
    {
        $testRequestTimeFilterArrivalSearch = new RequestTimeFilterArrivalSearch();
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "departureLocationIds"
     */
    public function testPropertyDepartureLocationIds()
    {
    }

    /**
     * Test attribute "arrivalLocationId"
     */
    public function testPropertyArrivalLocationId()
    {
    }

    /**
     * Test attribute "transportation"
     */
    public function testPropertyTransportation()
    {
    }

    /**
     * Test attribute "travelTime"
     */
    public function testPropertyTravelTime()
    {
    }

    /**
     * Test attribute "arrivalTime"
     */
    public function testPropertyArrivalTime()
    {
    }

    /**
     * Test attribute "properties"
     */
    public function testPropertyProperties()
    {
    }

    /**
     * Test attribute "range"
     */
    public function testPropertyRange()
    {
    }
}
