<?php
/**
 * ResponseTimeFilterPostcodeSectorsResultTest
 *
 * PHP version 7.1.3
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * TravelTime API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support@igeolise.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\TestCase;

/**
 * ResponseTimeFilterPostcodeSectorsResultTest Class Doc Comment
 *
 * @category    Class */
// * @description ResponseTimeFilterPostcodeSectorsResult
/**
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class ResponseTimeFilterPostcodeSectorsResultTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseTimeFilterPostcodeSectorsResult"
     */
    public function testResponseTimeFilterPostcodeSectorsResult()
    {
        $testResponseTimeFilterPostcodeSectorsResult = new ResponseTimeFilterPostcodeSectorsResult();
    }

    /**
     * Test attribute "searchId"
     */
    public function testPropertySearchId()
    {
    }

    /**
     * Test attribute "sectors"
     */
    public function testPropertySectors()
    {
    }
}
