/*
 * request_time_filter_postcode_sectors_property.h
 *
 * 
 */

#ifndef _request_time_filter_postcode_sectors_property_H_
#define _request_time_filter_postcode_sectors_property_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"

// Enum  for request_time_filter_postcode_sectors_property

typedef enum { traveltime_platform_api_request_time_filter_postcode_sectors_property__NULL = 0, traveltime_platform_api_request_time_filter_postcode_sectors_property__travel_time_reachable, traveltime_platform_api_request_time_filter_postcode_sectors_property__travel_time_all, traveltime_platform_api_request_time_filter_postcode_sectors_property__coverage } traveltime_platform_api_request_time_filter_postcode_sectors_property__e;

char* request_time_filter_postcode_sectors_property_request_time_filter_postcode_sectors_property_ToString(traveltime_platform_api_request_time_filter_postcode_sectors_property__e request_time_filter_postcode_sectors_property);

traveltime_platform_api_request_time_filter_postcode_sectors_property__e request_time_filter_postcode_sectors_property_request_time_filter_postcode_sectors_property_FromString(char* request_time_filter_postcode_sectors_property);

//cJSON *request_time_filter_postcode_sectors_property_request_time_filter_postcode_sectors_property_convertToJSON(traveltime_platform_api_request_time_filter_postcode_sectors_property__e request_time_filter_postcode_sectors_property);

//traveltime_platform_api_request_time_filter_postcode_sectors_property__e request_time_filter_postcode_sectors_property_request_time_filter_postcode_sectors_property_parseFromJSON(cJSON *request_time_filter_postcode_sectors_propertyJSON);

#endif /* _request_time_filter_postcode_sectors_property_H_ */

