/*
 * response_distance_breakdown_item.h
 *
 * 
 */

#ifndef _response_distance_breakdown_item_H_
#define _response_distance_breakdown_item_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct response_distance_breakdown_item_t response_distance_breakdown_item_t;

#include "response_transportation_mode.h"

// Enum  for response_distance_breakdown_item

typedef enum  { traveltime_api_response_distance_breakdown_item__NULL = 0, traveltime_api_response_distance_breakdown_item__car, traveltime_api_response_distance_breakdown_item__parking, traveltime_api_response_distance_breakdown_item__boarding, traveltime_api_response_distance_breakdown_item__walk, traveltime_api_response_distance_breakdown_item__bike, traveltime_api_response_distance_breakdown_item__train, traveltime_api_response_distance_breakdown_item__rail_national, traveltime_api_response_distance_breakdown_item__rail_overground, traveltime_api_response_distance_breakdown_item__rail_underground, traveltime_api_response_distance_breakdown_item__rail_dlr, traveltime_api_response_distance_breakdown_item__bus, traveltime_api_response_distance_breakdown_item__cable_car, traveltime_api_response_distance_breakdown_item__plane, traveltime_api_response_distance_breakdown_item__ferry, traveltime_api_response_distance_breakdown_item__coach } traveltime_api_response_distance_breakdown_item__e;

char* response_distance_breakdown_item_mode_ToString(traveltime_api_response_distance_breakdown_item__e mode);

traveltime_api_response_distance_breakdown_item__e response_distance_breakdown_item_mode_FromString(char* mode);



typedef struct response_distance_breakdown_item_t {
    int distance; //numeric

} response_distance_breakdown_item_t;

response_distance_breakdown_item_t *response_distance_breakdown_item_create(
    int distance
);

void response_distance_breakdown_item_free(response_distance_breakdown_item_t *response_distance_breakdown_item);

response_distance_breakdown_item_t *response_distance_breakdown_item_parseFromJSON(cJSON *response_distance_breakdown_itemJSON);

cJSON *response_distance_breakdown_item_convertToJSON(response_distance_breakdown_item_t *response_distance_breakdown_item);

#endif /* _response_distance_breakdown_item_H_ */

