/*
 * response_transportation_mode.h
 *
 * 
 */

#ifndef _response_transportation_mode_H_
#define _response_transportation_mode_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct response_transportation_mode_t response_transportation_mode_t;


// Enum  for response_transportation_mode

typedef enum { traveltime_api_response_transportation_mode__NULL = 0, traveltime_api_response_transportation_mode__car, traveltime_api_response_transportation_mode__parking, traveltime_api_response_transportation_mode__boarding, traveltime_api_response_transportation_mode__walk, traveltime_api_response_transportation_mode__bike, traveltime_api_response_transportation_mode__train, traveltime_api_response_transportation_mode__rail_national, traveltime_api_response_transportation_mode__rail_overground, traveltime_api_response_transportation_mode__rail_underground, traveltime_api_response_transportation_mode__rail_dlr, traveltime_api_response_transportation_mode__bus, traveltime_api_response_transportation_mode__cable_car, traveltime_api_response_transportation_mode__plane, traveltime_api_response_transportation_mode__ferry, traveltime_api_response_transportation_mode__coach } traveltime_api_response_transportation_mode__e;

char* response_transportation_mode_response_transportation_mode_ToString(traveltime_api_response_transportation_mode__e response_transportation_mode);

traveltime_api_response_transportation_mode__e response_transportation_mode_response_transportation_mode_FromString(char* response_transportation_mode);

//cJSON *response_transportation_mode_response_transportation_mode_convertToJSON(traveltime_api_response_transportation_mode__e response_transportation_mode);

//traveltime_api_response_transportation_mode__e response_transportation_mode_response_transportation_mode_parseFromJSON(cJSON *response_transportation_modeJSON);

#endif /* _response_transportation_mode_H_ */

