/* 
 * TravelTime Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@igeolise.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing RequestTimeFilterPostcodesDepartureSearch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestTimeFilterPostcodesDepartureSearchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestTimeFilterPostcodesDepartureSearch
        //private RequestTimeFilterPostcodesDepartureSearch instance;

        public RequestTimeFilterPostcodesDepartureSearchTests()
        {
            // TODO uncomment below to create an instance of RequestTimeFilterPostcodesDepartureSearch
            //instance = new RequestTimeFilterPostcodesDepartureSearch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestTimeFilterPostcodesDepartureSearch
        /// </summary>
        [Fact]
        public void RequestTimeFilterPostcodesDepartureSearchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RequestTimeFilterPostcodesDepartureSearch
            //Assert.IsInstanceOfType<RequestTimeFilterPostcodesDepartureSearch> (instance, "variable 'instance' is a RequestTimeFilterPostcodesDepartureSearch");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Transportation'
        /// </summary>
        [Fact]
        public void TransportationTest()
        {
            // TODO unit test for the property 'Transportation'
        }
        /// <summary>
        /// Test the property 'TravelTime'
        /// </summary>
        [Fact]
        public void TravelTimeTest()
        {
            // TODO unit test for the property 'TravelTime'
        }
        /// <summary>
        /// Test the property 'DepartureTime'
        /// </summary>
        [Fact]
        public void DepartureTimeTest()
        {
            // TODO unit test for the property 'DepartureTime'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'Range'
        /// </summary>
        [Fact]
        public void RangeTest()
        {
            // TODO unit test for the property 'Range'
        }

    }

}
