/* 
 * TravelTime Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@igeolise.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing RequestTimeFilterPostcodeSectors
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestTimeFilterPostcodeSectorsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestTimeFilterPostcodeSectors
        //private RequestTimeFilterPostcodeSectors instance;

        public RequestTimeFilterPostcodeSectorsTests()
        {
            // TODO uncomment below to create an instance of RequestTimeFilterPostcodeSectors
            //instance = new RequestTimeFilterPostcodeSectors();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestTimeFilterPostcodeSectors
        /// </summary>
        [Fact]
        public void RequestTimeFilterPostcodeSectorsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RequestTimeFilterPostcodeSectors
            //Assert.IsInstanceOfType<RequestTimeFilterPostcodeSectors> (instance, "variable 'instance' is a RequestTimeFilterPostcodeSectors");
        }


        /// <summary>
        /// Test the property 'DepartureSearches'
        /// </summary>
        [Fact]
        public void DepartureSearchesTest()
        {
            // TODO unit test for the property 'DepartureSearches'
        }
        /// <summary>
        /// Test the property 'ArrivalSearches'
        /// </summary>
        [Fact]
        public void ArrivalSearchesTest()
        {
            // TODO unit test for the property 'ArrivalSearches'
        }

    }

}
