/* 
 * TravelTime API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support@igeolise.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ResponseDistanceBreakdownItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseDistanceBreakdownItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseDistanceBreakdownItem
        //private ResponseDistanceBreakdownItem instance;

        public ResponseDistanceBreakdownItemTests()
        {
            // TODO uncomment below to create an instance of ResponseDistanceBreakdownItem
            //instance = new ResponseDistanceBreakdownItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseDistanceBreakdownItem
        /// </summary>
        [Fact]
        public void ResponseDistanceBreakdownItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseDistanceBreakdownItem
            //Assert.IsInstanceOfType<ResponseDistanceBreakdownItem> (instance, "variable 'instance' is a ResponseDistanceBreakdownItem");
        }


        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Fact]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }

    }

}
