<?php
/**
 * ResponseTimeMapWktResult
 *
 * PHP version 7
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

/**
 * ResponseTimeMapWktResult
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class ResponseTimeMapWktResult
{
    
    /** @var string $searchId */
    private $searchId;
    
    /** @var string $shape */
    private $shape;
    
    /** @var \OpenAPIServer\Model\ResponseTimeMapProperties $properties */
    private $properties;
}
