<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TravelTime Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for geocodingReverseSearch
     *
     * .
     *
     */
    public function testGeocodingReverseSearch()
    {
    }

    /**
     * Test case for geocodingSearch
     *
     * .
     *
     */
    public function testGeocodingSearch()
    {
    }

    /**
     * Test case for mapInfo
     *
     * .
     *
     */
    public function testMapInfo()
    {
    }

    /**
     * Test case for routes
     *
     * .
     *
     */
    public function testRoutes()
    {
    }

    /**
     * Test case for supportedLocations
     *
     * .
     *
     */
    public function testSupportedLocations()
    {
    }

    /**
     * Test case for timeFilter
     *
     * .
     *
     */
    public function testTimeFilter()
    {
    }

    /**
     * Test case for timeFilterFast
     *
     * .
     *
     */
    public function testTimeFilterFast()
    {
    }

    /**
     * Test case for timeFilterPostcodeDistricts
     *
     * .
     *
     */
    public function testTimeFilterPostcodeDistricts()
    {
    }

    /**
     * Test case for timeFilterPostcodeSectors
     *
     * .
     *
     */
    public function testTimeFilterPostcodeSectors()
    {
    }

    /**
     * Test case for timeFilterPostcodes
     *
     * .
     *
     */
    public function testTimeFilterPostcodes()
    {
    }

    /**
     * Test case for timeMap
     *
     * .
     *
     */
    public function testTimeMap()
    {
    }
}
