--[[
  TravelTime Platform API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  The version of the OpenAPI document: 1.0.0
  Contact: support@igeolise.com
  Generated by: https://openapi-generator.tech
]]

-- response_time_filter_properties class
local response_time_filter_properties = {}
local response_time_filter_properties_mt = {
	__name = "response_time_filter_properties";
	__index = response_time_filter_properties;
}

local function cast_response_time_filter_properties(t)
	return setmetatable(t, response_time_filter_properties_mt)
end

local function new_response_time_filter_properties(travel_time, distance, distance_breakdown, fares, route)
	return cast_response_time_filter_properties({
		["travel_time"] = travel_time;
		["distance"] = distance;
		["distance_breakdown"] = distance_breakdown;
		["fares"] = fares;
		["route"] = route;
	})
end

return {
	cast = cast_response_time_filter_properties;
	new = new_response_time_filter_properties;
}
