(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    name: string;
    features: Response_map_info_features.t;
} [@@deriving yojson { strict = false }, show ];;

let create (name : string) (features : Response_map_info_features.t) : t = {
    name = name;
    features = features;
}

