#
# TravelTime API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 1.2.2
# Contact: support@igeolise.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER IsOnlyWalking
No description available.
.OUTPUTS

ResponseTimeMapProperties<PSCustomObject>
#>

function Initialize-ResponseTimeMapProperties {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsOnlyWalking}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ResponseTimeMapProperties' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "is_only_walking" = ${IsOnlyWalking}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ResponseTimeMapProperties<PSCustomObject>

.DESCRIPTION

Convert from JSON to ResponseTimeMapProperties<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ResponseTimeMapProperties<PSCustomObject>
#>
function ConvertFrom-JsonToResponseTimeMapProperties {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ResponseTimeMapProperties' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ResponseTimeMapProperties
        $AllProperties = ("is_only_walking")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "is_only_walking"))) { #optional property not found
            $IsOnlyWalking = $null
        } else {
            $IsOnlyWalking = $JsonParameters.PSobject.Properties["is_only_walking"].value
        }

        $PSO = [PSCustomObject]@{
            "is_only_walking" = ${IsOnlyWalking}
        }

        return $PSO
    }

}

