{-
   TravelTime Platform API
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI spec version: 1.0.0
   Contact: support@igeolise.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.RequestTimeMap exposing (RequestTimeMap, decoder, encoder)

import Data.RequestTimeMapDepartureSearch as RequestTimeMapDepartureSearch exposing (RequestTimeMapDepartureSearch)
import Data.RequestTimeMapArrivalSearch as RequestTimeMapArrivalSearch exposing (RequestTimeMapArrivalSearch)
import Data.RequestUnionOnIntersection as RequestUnionOnIntersection exposing (RequestUnionOnIntersection)
import Data.RequestUnionOnIntersection as RequestUnionOnIntersection exposing (RequestUnionOnIntersection)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias RequestTimeMap =
    { departureSearches : Maybe ((List RequestTimeMapDepartureSearch))
    , arrivalSearches : Maybe ((List RequestTimeMapArrivalSearch))
    , unions : Maybe ((List RequestUnionOnIntersection))
    , intersections : Maybe ((List RequestUnionOnIntersection))
    }


decoder : Decoder RequestTimeMap
decoder =
    Decode.succeed RequestTimeMap
        |> optional "departure_searches" (Decode.nullable (Decode.list RequestTimeMapDepartureSearch.decoder)) Nothing
        |> optional "arrival_searches" (Decode.nullable (Decode.list RequestTimeMapArrivalSearch.decoder)) Nothing
        |> optional "unions" (Decode.nullable (Decode.list RequestUnionOnIntersection.decoder)) Nothing
        |> optional "intersections" (Decode.nullable (Decode.list RequestUnionOnIntersection.decoder)) Nothing



encoder : RequestTimeMap -> Encode.Value
encoder model =
    Encode.object
        [ ( "departure_searches", Maybe.withDefault Encode.null (Maybe.map (Encode.list RequestTimeMapDepartureSearch.encoder) model.departureSearches) )
        , ( "arrival_searches", Maybe.withDefault Encode.null (Maybe.map (Encode.list RequestTimeMapArrivalSearch.encoder) model.arrivalSearches) )
        , ( "unions", Maybe.withDefault Encode.null (Maybe.map (Encode.list RequestUnionOnIntersection.encoder) model.unions) )
        , ( "intersections", Maybe.withDefault Encode.null (Maybe.map (Encode.list RequestUnionOnIntersection.encoder) model.intersections) )

        ]


