/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ResponseBox {
    'minLat': number;
    'maxLat': number;
    'minLng': number;
    'maxLng': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "minLat",
            "baseName": "min_lat",
            "type": "number"
        },
        {
            "name": "maxLat",
            "baseName": "max_lat",
            "type": "number"
        },
        {
            "name": "minLng",
            "baseName": "min_lng",
            "type": "number"
        },
        {
            "name": "maxLng",
            "baseName": "max_lng",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ResponseBox.attributeTypeMap;
    }
}

