/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Coords } from './coords';

export class ResponseShape {
    'shell': Array<Coords>;
    'holes': Array<Array<Coords>>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shell",
            "baseName": "shell",
            "type": "Array<Coords>"
        },
        {
            "name": "holes",
            "baseName": "holes",
            "type": "Array<Array<Coords>>"
        }    ];

    static getAttributeTypeMap() {
        return ResponseShape.attributeTypeMap;
    }
}

