/**
 * TravelTime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ResponseFareTicket } from './responseFareTicket';
import { ResponseFaresBreakdownItem } from './responseFaresBreakdownItem';

export class ResponseFares {
    'breakdown': Array<ResponseFaresBreakdownItem>;
    'ticketsTotal': Array<ResponseFareTicket>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "breakdown",
            "baseName": "breakdown",
            "type": "Array<ResponseFaresBreakdownItem>"
        },
        {
            "name": "ticketsTotal",
            "baseName": "tickets_total",
            "type": "Array<ResponseFareTicket>"
        }    ];

    static getAttributeTypeMap() {
        return ResponseFares.attributeTypeMap;
    }
}

