/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ResponseFaresFast } from './responseFaresFast';

export class ResponseTimeFilterFastProperties {
    'travelTime'?: number;
    'fares'?: ResponseFaresFast;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "travelTime",
            "baseName": "travel_time",
            "type": "number"
        },
        {
            "name": "fares",
            "baseName": "fares",
            "type": "ResponseFaresFast"
        }    ];

    static getAttributeTypeMap() {
        return ResponseTimeFilterFastProperties.attributeTypeMap;
    }
}

