#
# TravelTime API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 1.2.3
# Contact: support@igeolise.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RequestTimeFilterPostcodeDistrictsProperty' {
    Context 'RequestTimeFilterPostcodeDistrictsProperty' {
        It 'Initialize-RequestTimeFilterPostcodeDistrictsProperty' {
            # a simple test to create an object
            #$NewObject = Initialize-RequestTimeFilterPostcodeDistrictsProperty
            #$NewObject | Should -BeOfType RequestTimeFilterPostcodeDistrictsProperty
            #$NewObject.property | Should -Be 0
        }
    }
}
