#
# TravelTime API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 1.2.2
# Contact: support@igeolise.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RequestTimeFilterPostcodeSectorsProperty' {
    Context 'RequestTimeFilterPostcodeSectorsProperty' {
        It 'Initialize-RequestTimeFilterPostcodeSectorsProperty' {
            # a simple test to create an object
            #$NewObject = Initialize-RequestTimeFilterPostcodeSectorsProperty
            #$NewObject | Should -BeOfType RequestTimeFilterPostcodeSectorsProperty
            #$NewObject.property | Should -Be 0
        }
    }
}
