//
// ResponseTravelTimeStatistics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


open class ResponseTravelTimeStatistics: JSONEncodable {

    public var min: Int32?
    public var max: Int32?
    public var mean: Int32?
    public var median: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["min"] = self.min?.encodeToJSON()
        nillableDictionary["max"] = self.max?.encodeToJSON()
        nillableDictionary["mean"] = self.mean?.encodeToJSON()
        nillableDictionary["median"] = self.median?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

