/**
* TravelTime Platform API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: support@igeolise.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "RequestTimeFilterDepartureSearch.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

RequestTimeFilterDepartureSearch::RequestTimeFilterDepartureSearch()
{
    m_Id = "";
    m_Departure_location_id = "";
    m_Travel_time = 0;
    m_Departure_time = "";
    m_RangeIsSet = false;
    
}

RequestTimeFilterDepartureSearch::~RequestTimeFilterDepartureSearch()
{
}

void RequestTimeFilterDepartureSearch::validate()
{
    // TODO: implement validation
}

void to_json(nlohmann::json& j, const RequestTimeFilterDepartureSearch& o)
{
    j = nlohmann::json();
    j["id"] = o.m_Id;
    j["departure_location_id"] = o.m_Departure_location_id;
    j["arrival_location_ids"] = o.m_Arrival_location_ids;
    j["transportation"] = o.m_Transportation;
    j["travel_time"] = o.m_Travel_time;
    j["departure_time"] = o.m_Departure_time;
    j["properties"] = o.m_Properties;
    if(o.rangeIsSet())
        j["range"] = o.m_Range;
}

void from_json(const nlohmann::json& j, RequestTimeFilterDepartureSearch& o)
{
    j.at("id").get_to(o.m_Id);
    j.at("departure_location_id").get_to(o.m_Departure_location_id);
    j.at("arrival_location_ids").get_to(o.m_Arrival_location_ids);
    j.at("transportation").get_to(o.m_Transportation);
    j.at("travel_time").get_to(o.m_Travel_time);
    j.at("departure_time").get_to(o.m_Departure_time);
    j.at("properties").get_to(o.m_Properties);
    if(j.contains("range"))
    {
        j.at("range").get_to(o.m_Range);
        o.m_RangeIsSet = true;
    } 
}

std::string RequestTimeFilterDepartureSearch::getId() const
{
    return m_Id;
}
void RequestTimeFilterDepartureSearch::setId(std::string const& value)
{
    m_Id = value;
    
}
std::string RequestTimeFilterDepartureSearch::getDepartureLocationId() const
{
    return m_Departure_location_id;
}
void RequestTimeFilterDepartureSearch::setDepartureLocationId(std::string const& value)
{
    m_Departure_location_id = value;
    
}
std::vector<std::string>& RequestTimeFilterDepartureSearch::getArrivalLocationIds()
{
    return m_Arrival_location_ids;
}
RequestTransportation RequestTimeFilterDepartureSearch::getTransportation() const
{
    return m_Transportation;
}
void RequestTimeFilterDepartureSearch::setTransportation(RequestTransportation const& value)
{
    m_Transportation = value;
    
}
int32_t RequestTimeFilterDepartureSearch::getTravelTime() const
{
    return m_Travel_time;
}
void RequestTimeFilterDepartureSearch::setTravelTime(int32_t const value)
{
    m_Travel_time = value;
    
}
std::string RequestTimeFilterDepartureSearch::getDepartureTime() const
{
    return m_Departure_time;
}
void RequestTimeFilterDepartureSearch::setDepartureTime(std::string const& value)
{
    m_Departure_time = value;
    
}
std::vector<RequestTimeFilterProperty>& RequestTimeFilterDepartureSearch::getProperties()
{
    return m_Properties;
}
RequestRangeFull RequestTimeFilterDepartureSearch::getRange() const
{
    return m_Range;
}
void RequestTimeFilterDepartureSearch::setRange(RequestRangeFull const& value)
{
    m_Range = value;
    m_RangeIsSet = true;
}
bool RequestTimeFilterDepartureSearch::rangeIsSet() const
{
    return m_RangeIsSet;
}
void RequestTimeFilterDepartureSearch::unsetRange()
{
    m_RangeIsSet = false;
}

}
}
}
}

