/**
* TravelTime API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.2.2
* Contact: support@igeolise.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RequestArrivalTimePeriod.h
 *
 * 
 */

#ifndef RequestArrivalTimePeriod_H_
#define RequestArrivalTimePeriod_H_


#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  RequestArrivalTimePeriod
{
public:
    RequestArrivalTimePeriod();
    virtual ~RequestArrivalTimePeriod() = default;

    enum class eRequestArrivalTimePeriod {
    // To have a valid default value.
    // Avoiding nameclashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    WEEKDAY_MORNING
    };

    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    bool operator==(const RequestArrivalTimePeriod& rhs) const;
    bool operator!=(const RequestArrivalTimePeriod& rhs) const;

    /////////////////////////////////////////////
    /// RequestArrivalTimePeriod members

    RequestArrivalTimePeriod::eRequestArrivalTimePeriod getValue() const;
    void setValue(RequestArrivalTimePeriod::eRequestArrivalTimePeriod value);

    friend void to_json(nlohmann::json& j, const RequestArrivalTimePeriod& o);
    friend void from_json(const nlohmann::json& j, RequestArrivalTimePeriod& o);
protected:
    RequestArrivalTimePeriod::eRequestArrivalTimePeriod m_value = RequestArrivalTimePeriod::eRequestArrivalTimePeriod::INVALID_VALUE_OPENAPI_GENERATED;

    // Helper overload for validate. Used when one model stores another model and calls it's validate.
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

} // namespace org::openapitools::server::model

#endif /* RequestArrivalTimePeriod_H_ */
