/**
* TravelTime API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.2.3
* Contact: support@igeolise.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "RequestTimeFilterPostcodeDistricts.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

RequestTimeFilterPostcodeDistricts::RequestTimeFilterPostcodeDistricts()
{
    m_Departure_searchesIsSet = false;
    m_Arrival_searchesIsSet = false;
    
}

void RequestTimeFilterPostcodeDistricts::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool RequestTimeFilterPostcodeDistricts::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool RequestTimeFilterPostcodeDistricts::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "RequestTimeFilterPostcodeDistricts" : pathPrefix;

         
    if (departureSearchesIsSet())
    {
        const std::vector<RequestTimeFilterPostcodeDistrictsDepartureSearch>& value = m_Departure_searches;
        const std::string currentValuePath = _pathPrefix + ".departureSearches";
                
        
        if (value.size() > 10)
        {
            success = false;
            msg << currentValuePath << ": must have at most 10 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const RequestTimeFilterPostcodeDistrictsDepartureSearch& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".departureSearches") && success;
 
                i++;
            }
        }

    }
    
     
    if (arrivalSearchesIsSet())
    {
        const std::vector<RequestTimeFilterPostcodeDistrictsArrivalSearch>& value = m_Arrival_searches;
        const std::string currentValuePath = _pathPrefix + ".arrivalSearches";
                
        
        if (value.size() > 10)
        {
            success = false;
            msg << currentValuePath << ": must have at most 10 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const RequestTimeFilterPostcodeDistrictsArrivalSearch& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".arrivalSearches") && success;
 
                i++;
            }
        }

    }
    

    return success;
}

bool RequestTimeFilterPostcodeDistricts::operator==(const RequestTimeFilterPostcodeDistricts& rhs) const
{
    return
    
    
    
    ((!departureSearchesIsSet() && !rhs.departureSearchesIsSet()) || (departureSearchesIsSet() && rhs.departureSearchesIsSet() && getDepartureSearches() == rhs.getDepartureSearches())) &&
    
    
    ((!arrivalSearchesIsSet() && !rhs.arrivalSearchesIsSet()) || (arrivalSearchesIsSet() && rhs.arrivalSearchesIsSet() && getArrivalSearches() == rhs.getArrivalSearches()))
    
    ;
}

bool RequestTimeFilterPostcodeDistricts::operator!=(const RequestTimeFilterPostcodeDistricts& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const RequestTimeFilterPostcodeDistricts& o)
{
    j = nlohmann::json();
    if(o.departureSearchesIsSet() || !o.m_Departure_searches.empty())
        j["departure_searches"] = o.m_Departure_searches;
    if(o.arrivalSearchesIsSet() || !o.m_Arrival_searches.empty())
        j["arrival_searches"] = o.m_Arrival_searches;
    
}

void from_json(const nlohmann::json& j, RequestTimeFilterPostcodeDistricts& o)
{
    if(j.find("departure_searches") != j.end())
    {
        j.at("departure_searches").get_to(o.m_Departure_searches);
        o.m_Departure_searchesIsSet = true;
    } 
    if(j.find("arrival_searches") != j.end())
    {
        j.at("arrival_searches").get_to(o.m_Arrival_searches);
        o.m_Arrival_searchesIsSet = true;
    } 
    
}

std::vector<RequestTimeFilterPostcodeDistrictsDepartureSearch> RequestTimeFilterPostcodeDistricts::getDepartureSearches() const
{
    return m_Departure_searches;
}
void RequestTimeFilterPostcodeDistricts::setDepartureSearches(std::vector<RequestTimeFilterPostcodeDistrictsDepartureSearch> const& value)
{
    m_Departure_searches = value;
    m_Departure_searchesIsSet = true;
}
bool RequestTimeFilterPostcodeDistricts::departureSearchesIsSet() const
{
    return m_Departure_searchesIsSet;
}
void RequestTimeFilterPostcodeDistricts::unsetDeparture_searches()
{
    m_Departure_searchesIsSet = false;
}
std::vector<RequestTimeFilterPostcodeDistrictsArrivalSearch> RequestTimeFilterPostcodeDistricts::getArrivalSearches() const
{
    return m_Arrival_searches;
}
void RequestTimeFilterPostcodeDistricts::setArrivalSearches(std::vector<RequestTimeFilterPostcodeDistrictsArrivalSearch> const& value)
{
    m_Arrival_searches = value;
    m_Arrival_searchesIsSet = true;
}
bool RequestTimeFilterPostcodeDistricts::arrivalSearchesIsSet() const
{
    return m_Arrival_searchesIsSet;
}
void RequestTimeFilterPostcodeDistricts::unsetArrival_searches()
{
    m_Arrival_searchesIsSet = false;
}


} // namespace org::openapitools::server::model

