/**
* TravelTime Platform API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* Contact: support@igeolise.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ResponseTimeFilterPostcodeSector.h
 *
 * 
 */

#ifndef ResponseTimeFilterPostcodeSector_H_
#define ResponseTimeFilterPostcodeSector_H_


#include "ResponseTimeFilterPostcodeSectorProperties.h"
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  ResponseTimeFilterPostcodeSector
{
public:
    ResponseTimeFilterPostcodeSector();
    virtual ~ResponseTimeFilterPostcodeSector();

    void validate();

    /////////////////////////////////////////////
    /// ResponseTimeFilterPostcodeSector members

    /// <summary>
    /// 
    /// </summary>
    String getCode() const;
    void setCode(String const& value);
    /// <summary>
    /// 
    /// </summary>
    ResponseTimeFilterPostcodeSectorProperties getProperties() const;
    void setProperties(ResponseTimeFilterPostcodeSectorProperties const& value);

    friend void to_json(nlohmann::json& j, const ResponseTimeFilterPostcodeSector& o);
    friend void from_json(const nlohmann::json& j, ResponseTimeFilterPostcodeSector& o);
protected:
    String m_Code;

    ResponseTimeFilterPostcodeSectorProperties m_Properties;

};

}
}
}
}

#endif /* ResponseTimeFilterPostcodeSector_H_ */
