/**
* TravelTime Platform API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 1.0.0
* Contact: support@igeolise.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ResponseTimeMapWkt.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

ResponseTimeMapWkt::ResponseTimeMapWkt()
{
    
}

ResponseTimeMapWkt::~ResponseTimeMapWkt()
{
}

void ResponseTimeMapWkt::validate()
{
    // TODO: implement validation
}

nlohmann::json ResponseTimeMapWkt::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    {
        nlohmann::json jsonArray;
        for( auto& item : m_Results )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        val["results"] = jsonArray;
        
    }
    

    return val;
}

void ResponseTimeMapWkt::fromJson(const nlohmann::json& val)
{
    {
        m_Results.clear();
                    for( auto& item : val["results"] )
            {
                
                if(item.is_null())
                {
                    m_Results.push_back( ResponseTimeMapWktResult() );
                }
                else
                {
                    ResponseTimeMapWktResult newItem;
                    newItem.fromJson(item);
                    m_Results.push_back( newItem );
                }
                
            }
    }
    
}


std::vector<ResponseTimeMapWktResult>& ResponseTimeMapWkt::getResults()
{
    return m_Results;
}

}
}
}
}

