/**
* TravelTime Platform API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 1.0.0
* Contact: support@igeolise.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "ResponseTimeFilterPostcode.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

ResponseTimeFilterPostcode::ResponseTimeFilterPostcode()
{
    
}

ResponseTimeFilterPostcode::~ResponseTimeFilterPostcode()
{
}

void ResponseTimeFilterPostcode::validate()
{
    // TODO: implement validation
}

nlohmann::json ResponseTimeFilterPostcode::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    val["code"] = ModelBase::toJson(m_Code);
    {
        nlohmann::json jsonArray;
        for( auto& item : m_Properties )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        val["properties"] = jsonArray;
        
    }
    

    return val;
}

void ResponseTimeFilterPostcode::fromJson(const nlohmann::json& val)
{
    {
        m_Properties.clear();
                    for( auto& item : val["properties"] )
            {
                
                if(item.is_null())
                {
                    m_Properties.push_back( ResponseTimeFilterPostcodesProperties() );
                }
                else
                {
                    ResponseTimeFilterPostcodesProperties newItem;
                    newItem.fromJson(item);
                    m_Properties.push_back( newItem );
                }
                
            }
    }
    
}


String ResponseTimeFilterPostcode::getCode() const
{
    return m_Code;
}
void ResponseTimeFilterPostcode::setCode(String const& value)
{
    m_Code = value;
    
}
std::vector<ResponseTimeFilterPostcodesProperties>& ResponseTimeFilterPostcode::getProperties()
{
    return m_Properties;
}

}
}
}
}

