/**
* TravelTime Platform API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 1.0.0
* Contact: support@igeolise.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ResponseSupportedLocation.h
 *
 * 
 */

#ifndef ResponseSupportedLocation_H_
#define ResponseSupportedLocation_H_


#include "ModelBase.h"

#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  ResponseSupportedLocation
    : public ModelBase
{
public:
    ResponseSupportedLocation();
    virtual ~ResponseSupportedLocation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    nlohmann::json toJson() const override;
    void fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// ResponseSupportedLocation members

    /// <summary>
    /// 
    /// </summary>
    std::string getId() const;
    void setId(std::string const& value);
        /// <summary>
    /// 
    /// </summary>
    std::string getMapName() const;
    void setMapName(std::string const& value);
    
protected:
    std::string m_Id;

    std::string m_Map_name;

};

}
}
}
}

#endif /* ResponseSupportedLocation_H_ */
