/**
* TravelTime API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.2.1
* Contact: support@igeolise.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ResponseFareTicket.h
 *
 * 
 */

#ifndef ResponseFareTicket_H_
#define ResponseFareTicket_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org {
namespace openapitools {
namespace server {
namespace model {

/// <summary>
/// 
/// </summary>
class  ResponseFareTicket
{
public:
    ResponseFareTicket();
    virtual ~ResponseFareTicket();

    void validate();

    /////////////////////////////////////////////
    /// ResponseFareTicket members

    /// <summary>
    /// 
    /// </summary>
    std::string getType() const;
    void setType(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    double getPrice() const;
    void setPrice(double const value);
    /// <summary>
    /// 
    /// </summary>
    std::string getCurrency() const;
    void setCurrency(std::string const& value);

    friend void to_json(nlohmann::json& j, const ResponseFareTicket& o);
    friend void from_json(const nlohmann::json& j, ResponseFareTicket& o);
protected:
    std::string m_Type;

    double m_Price;

    std::string m_Currency;

};

}
}
}
}

#endif /* ResponseFareTicket_H_ */
