<?php
/**
 * RequestTransportationTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TravelTime API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support@igeolise.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * RequestTransportationTest Class Doc Comment
 *
 * @category    Class
 * @description RequestTransportation
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RequestTransportationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RequestTransportation"
     */
    public function testRequestTransportation()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "pt_change_delay"
     */
    public function testPropertyPtChangeDelay()
    {
    }

    /**
     * Test attribute "walking_time"
     */
    public function testPropertyWalkingTime()
    {
    }

    /**
     * Test attribute "driving_time_to_station"
     */
    public function testPropertyDrivingTimeToStation()
    {
    }

    /**
     * Test attribute "parking_time"
     */
    public function testPropertyParkingTime()
    {
    }

    /**
     * Test attribute "boarding_time"
     */
    public function testPropertyBoardingTime()
    {
    }
}
