/*
 * TravelTime API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.1
 * Contact: support@igeolise.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ResponseTimeMapProperties struct for ResponseTimeMapProperties
type ResponseTimeMapProperties struct {
	IsOnlyWalking bool `json:"is_only_walking,omitempty"`
}
