/*
 * TravelTime API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.2.3
 * Contact: support@igeolise.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RequestTimeFilterFastArrivalOneToManySearch struct for RequestTimeFilterFastArrivalOneToManySearch
type RequestTimeFilterFastArrivalOneToManySearch struct {
	Id string `json:"id"`
	DepartureLocationId string `json:"departure_location_id"`
	ArrivalLocationIds []string `json:"arrival_location_ids"`
	Transportation RequestTransportationFast `json:"transportation"`
	TravelTime int32 `json:"travel_time"`
	ArrivalTimePeriod RequestArrivalTimePeriod `json:"arrival_time_period"`
	Properties []RequestTimeFilterFastProperty `json:"properties"`
}

// NewRequestTimeFilterFastArrivalOneToManySearch instantiates a new RequestTimeFilterFastArrivalOneToManySearch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestTimeFilterFastArrivalOneToManySearch(id string, departureLocationId string, arrivalLocationIds []string, transportation RequestTransportationFast, travelTime int32, arrivalTimePeriod RequestArrivalTimePeriod, properties []RequestTimeFilterFastProperty) *RequestTimeFilterFastArrivalOneToManySearch {
	this := RequestTimeFilterFastArrivalOneToManySearch{}
	this.Id = id
	this.DepartureLocationId = departureLocationId
	this.ArrivalLocationIds = arrivalLocationIds
	this.Transportation = transportation
	this.TravelTime = travelTime
	this.ArrivalTimePeriod = arrivalTimePeriod
	this.Properties = properties
	return &this
}

// NewRequestTimeFilterFastArrivalOneToManySearchWithDefaults instantiates a new RequestTimeFilterFastArrivalOneToManySearch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestTimeFilterFastArrivalOneToManySearchWithDefaults() *RequestTimeFilterFastArrivalOneToManySearch {
	this := RequestTimeFilterFastArrivalOneToManySearch{}
	return &this
}

// GetId returns the Id field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) SetId(v string) {
	o.Id = v
}

// GetDepartureLocationId returns the DepartureLocationId field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetDepartureLocationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DepartureLocationId
}

// GetDepartureLocationIdOk returns a tuple with the DepartureLocationId field value
// and a boolean to check if the value has been set.
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetDepartureLocationIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DepartureLocationId, true
}

// SetDepartureLocationId sets field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) SetDepartureLocationId(v string) {
	o.DepartureLocationId = v
}

// GetArrivalLocationIds returns the ArrivalLocationIds field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetArrivalLocationIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ArrivalLocationIds
}

// GetArrivalLocationIdsOk returns a tuple with the ArrivalLocationIds field value
// and a boolean to check if the value has been set.
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetArrivalLocationIdsOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ArrivalLocationIds, true
}

// SetArrivalLocationIds sets field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) SetArrivalLocationIds(v []string) {
	o.ArrivalLocationIds = v
}

// GetTransportation returns the Transportation field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetTransportation() RequestTransportationFast {
	if o == nil {
		var ret RequestTransportationFast
		return ret
	}

	return o.Transportation
}

// GetTransportationOk returns a tuple with the Transportation field value
// and a boolean to check if the value has been set.
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetTransportationOk() (*RequestTransportationFast, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Transportation, true
}

// SetTransportation sets field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) SetTransportation(v RequestTransportationFast) {
	o.Transportation = v
}

// GetTravelTime returns the TravelTime field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetTravelTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TravelTime
}

// GetTravelTimeOk returns a tuple with the TravelTime field value
// and a boolean to check if the value has been set.
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetTravelTimeOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TravelTime, true
}

// SetTravelTime sets field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) SetTravelTime(v int32) {
	o.TravelTime = v
}

// GetArrivalTimePeriod returns the ArrivalTimePeriod field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetArrivalTimePeriod() RequestArrivalTimePeriod {
	if o == nil {
		var ret RequestArrivalTimePeriod
		return ret
	}

	return o.ArrivalTimePeriod
}

// GetArrivalTimePeriodOk returns a tuple with the ArrivalTimePeriod field value
// and a boolean to check if the value has been set.
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetArrivalTimePeriodOk() (*RequestArrivalTimePeriod, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ArrivalTimePeriod, true
}

// SetArrivalTimePeriod sets field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) SetArrivalTimePeriod(v RequestArrivalTimePeriod) {
	o.ArrivalTimePeriod = v
}

// GetProperties returns the Properties field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetProperties() []RequestTimeFilterFastProperty {
	if o == nil {
		var ret []RequestTimeFilterFastProperty
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *RequestTimeFilterFastArrivalOneToManySearch) GetPropertiesOk() (*[]RequestTimeFilterFastProperty, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *RequestTimeFilterFastArrivalOneToManySearch) SetProperties(v []RequestTimeFilterFastProperty) {
	o.Properties = v
}

func (o RequestTimeFilterFastArrivalOneToManySearch) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["departure_location_id"] = o.DepartureLocationId
	}
	if true {
		toSerialize["arrival_location_ids"] = o.ArrivalLocationIds
	}
	if true {
		toSerialize["transportation"] = o.Transportation
	}
	if true {
		toSerialize["travel_time"] = o.TravelTime
	}
	if true {
		toSerialize["arrival_time_period"] = o.ArrivalTimePeriod
	}
	if true {
		toSerialize["properties"] = o.Properties
	}
	return json.Marshal(toSerialize)
}

type NullableRequestTimeFilterFastArrivalOneToManySearch struct {
	value *RequestTimeFilterFastArrivalOneToManySearch
	isSet bool
}

func (v NullableRequestTimeFilterFastArrivalOneToManySearch) Get() *RequestTimeFilterFastArrivalOneToManySearch {
	return v.value
}

func (v *NullableRequestTimeFilterFastArrivalOneToManySearch) Set(val *RequestTimeFilterFastArrivalOneToManySearch) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestTimeFilterFastArrivalOneToManySearch) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestTimeFilterFastArrivalOneToManySearch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestTimeFilterFastArrivalOneToManySearch(val *RequestTimeFilterFastArrivalOneToManySearch) *NullableRequestTimeFilterFastArrivalOneToManySearch {
	return &NullableRequestTimeFilterFastArrivalOneToManySearch{value: val, isSet: true}
}

func (v NullableRequestTimeFilterFastArrivalOneToManySearch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestTimeFilterFastArrivalOneToManySearch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


