<?php

/**
 * TravelTime API
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * The version of the OpenAPI document: 1.2.1
 * Contact: support@igeolise.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\DefaultApi;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\DefaultApi
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for geocodingReverseSearch
     *
     * .
     *
     * @covers ::geocodingReverseSearch
     */
    public function testGeocodingReverseSearch()
    {
        $this->markTestIncomplete(
            'Test of "geocodingReverseSearch" method has not been implemented yet.'
        );
    }

    /**
     * Test case for geocodingSearch
     *
     * .
     *
     * @covers ::geocodingSearch
     */
    public function testGeocodingSearch()
    {
        $this->markTestIncomplete(
            'Test of "geocodingSearch" method has not been implemented yet.'
        );
    }

    /**
     * Test case for mapInfo
     *
     * .
     *
     * @covers ::mapInfo
     */
    public function testMapInfo()
    {
        $this->markTestIncomplete(
            'Test of "mapInfo" method has not been implemented yet.'
        );
    }

    /**
     * Test case for routes
     *
     * .
     *
     * @covers ::routes
     */
    public function testRoutes()
    {
        $this->markTestIncomplete(
            'Test of "routes" method has not been implemented yet.'
        );
    }

    /**
     * Test case for supportedLocations
     *
     * .
     *
     * @covers ::supportedLocations
     */
    public function testSupportedLocations()
    {
        $this->markTestIncomplete(
            'Test of "supportedLocations" method has not been implemented yet.'
        );
    }

    /**
     * Test case for timeFilter
     *
     * .
     *
     * @covers ::timeFilter
     */
    public function testTimeFilter()
    {
        $this->markTestIncomplete(
            'Test of "timeFilter" method has not been implemented yet.'
        );
    }

    /**
     * Test case for timeFilterFast
     *
     * .
     *
     * @covers ::timeFilterFast
     */
    public function testTimeFilterFast()
    {
        $this->markTestIncomplete(
            'Test of "timeFilterFast" method has not been implemented yet.'
        );
    }

    /**
     * Test case for timeFilterPostcodeDistricts
     *
     * .
     *
     * @covers ::timeFilterPostcodeDistricts
     */
    public function testTimeFilterPostcodeDistricts()
    {
        $this->markTestIncomplete(
            'Test of "timeFilterPostcodeDistricts" method has not been implemented yet.'
        );
    }

    /**
     * Test case for timeFilterPostcodeSectors
     *
     * .
     *
     * @covers ::timeFilterPostcodeSectors
     */
    public function testTimeFilterPostcodeSectors()
    {
        $this->markTestIncomplete(
            'Test of "timeFilterPostcodeSectors" method has not been implemented yet.'
        );
    }

    /**
     * Test case for timeFilterPostcodes
     *
     * .
     *
     * @covers ::timeFilterPostcodes
     */
    public function testTimeFilterPostcodes()
    {
        $this->markTestIncomplete(
            'Test of "timeFilterPostcodes" method has not been implemented yet.'
        );
    }

    /**
     * Test case for timeMap
     *
     * .
     *
     * @covers ::timeMap
     */
    public function testTimeMap()
    {
        $this->markTestIncomplete(
            'Test of "timeMap" method has not been implemented yet.'
        );
    }
}
