/* 
 * TravelTime API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support@igeolise.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing RequestTimeFilterPostcodeDistricts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestTimeFilterPostcodeDistrictsTests
    {
        // TODO uncomment below to declare an instance variable for RequestTimeFilterPostcodeDistricts
        //private RequestTimeFilterPostcodeDistricts instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RequestTimeFilterPostcodeDistricts
            //instance = new RequestTimeFilterPostcodeDistricts();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RequestTimeFilterPostcodeDistricts
        /// </summary>
        [Test]
        public void RequestTimeFilterPostcodeDistrictsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RequestTimeFilterPostcodeDistricts
            //Assert.IsInstanceOf(typeof(RequestTimeFilterPostcodeDistricts), instance);
        }


        /// <summary>
        /// Test the property 'DepartureSearches'
        /// </summary>
        [Test]
        public void DepartureSearchesTest()
        {
            // TODO unit test for the property 'DepartureSearches'
        }
        /// <summary>
        /// Test the property 'ArrivalSearches'
        /// </summary>
        [Test]
        public void ArrivalSearchesTest()
        {
            // TODO unit test for the property 'ArrivalSearches'
        }

    }

}
