/**
 * TravelTime API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.3
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIResponseBoundingBox.h
 *
 * 
 */

#ifndef OAIResponseBoundingBox_H
#define OAIResponseBoundingBox_H

#include <QJsonObject>

#include "OAIResponseBox.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIResponseBoundingBox : public OAIObject {
public:
    OAIResponseBoundingBox();
    OAIResponseBoundingBox(QString json);
    ~OAIResponseBoundingBox() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIResponseBox getEnvelope() const;
    void setEnvelope(const OAIResponseBox &envelope);
    bool is_envelope_Set() const;
    bool is_envelope_Valid() const;

    QList<OAIResponseBox> getBoxes() const;
    void setBoxes(const QList<OAIResponseBox> &boxes);
    bool is_boxes_Set() const;
    bool is_boxes_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIResponseBox envelope;
    bool m_envelope_isSet;
    bool m_envelope_isValid;

    QList<OAIResponseBox> boxes;
    bool m_boxes_isSet;
    bool m_boxes_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIResponseBoundingBox)

#endif // OAIResponseBoundingBox_H
