/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIResponseDistanceBreakdownItem.h
 *
 * 
 */

#ifndef OAIResponseDistanceBreakdownItem_H
#define OAIResponseDistanceBreakdownItem_H

#include <QJsonObject>

#include "OAIResponseTransportationMode.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIResponseDistanceBreakdownItem : public OAIObject {
public:
    OAIResponseDistanceBreakdownItem();
    OAIResponseDistanceBreakdownItem(QString json);
    ~OAIResponseDistanceBreakdownItem() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIResponseTransportationMode getMode() const;
    void setMode(const OAIResponseTransportationMode &mode);

    qint32 getDistance() const;
    void setDistance(const qint32 &distance);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIResponseTransportationMode mode;
    bool m_mode_isSet;
    bool m_mode_isValid;

    qint32 distance;
    bool m_distance_isSet;
    bool m_distance_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIResponseDistanceBreakdownItem)

#endif // OAIResponseDistanceBreakdownItem_H
