/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIResponseTimeFilterPostcode.h
 *
 * 
 */

#ifndef OAIResponseTimeFilterPostcode_H
#define OAIResponseTimeFilterPostcode_H

#include <QJsonObject>


#include "OAIResponseTimeFilterPostcodesProperties.h"
#include <QList>

#include "OAIObject.h"
#include "OAIEnum.h"

namespace OpenAPI {

class OAIResponseTimeFilterPostcode: public OAIObject {
public:
    OAIResponseTimeFilterPostcode();
    OAIResponseTimeFilterPostcode(QString json);
    ~OAIResponseTimeFilterPostcode() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    String getCode() const;
    void setCode(const String &code);

    
    QList<OAIResponseTimeFilterPostcodesProperties> getProperties() const;
    void setProperties(const QList<OAIResponseTimeFilterPostcodesProperties> &properties);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    String code;
    bool m_code_isSet;
    bool m_code_isValid;
    
    QList<OAIResponseTimeFilterPostcodesProperties> properties;
    bool m_properties_isSet;
    bool m_properties_isValid;
    
    };

}

#endif // OAIResponseTimeFilterPostcode_H
