//
// RequestTimeMapProperty.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum RequestTimeMapProperty: String, Codable, CaseIterable {
    case isOnlyWalking = "is_only_walking"
}
