//
// ResponseTimeMapProperties.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ResponseTimeMapProperties: Codable { 


    public var isOnlyWalking: Bool?

    public init(isOnlyWalking: Bool? = nil) {
        self.isOnlyWalking = isOnlyWalking
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case isOnlyWalking = "is_only_walking"
    }

}
