/**
* TravelTime API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.2.1
* Contact: support@igeolise.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models

import org.openapitools.server.models.RequestRangeFull
import org.openapitools.server.models.RequestRoutesProperty
import org.openapitools.server.models.RequestTransportation

/**
 * 
 * @param id 
 * @param departureLocationIds 
 * @param arrivalLocationId 
 * @param transportation 
 * @param arrivalTime 
 * @param properties 
 * @param range 
 */
data class RequestRoutesArrivalSearch (
    val id: kotlin.String,
    val departureLocationIds: kotlin.Array<kotlin.String>,
    val arrivalLocationId: kotlin.String,
    val transportation: RequestTransportation,
    val arrivalTime: java.time.LocalDateTime,
    val properties: kotlin.Array<RequestRoutesProperty>,
    val range: RequestRangeFull? = null
) 

