# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.request_arrival_time_period import RequestArrivalTimePeriod
from openapi_server.models.request_time_filter_fast_property import RequestTimeFilterFastProperty
from openapi_server.models.request_transportation_fast import RequestTransportationFast
from openapi_server import util


class RequestTimeFilterFastArrivalManyToOneSearch(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, arrival_location_id: str=None, departure_location_ids: List[str]=None, transportation: RequestTransportationFast=None, travel_time: int=None, arrival_time_period: RequestArrivalTimePeriod=None, properties: List[RequestTimeFilterFastProperty]=None):
        """RequestTimeFilterFastArrivalManyToOneSearch - a model defined in OpenAPI

        :param id: The id of this RequestTimeFilterFastArrivalManyToOneSearch.
        :param arrival_location_id: The arrival_location_id of this RequestTimeFilterFastArrivalManyToOneSearch.
        :param departure_location_ids: The departure_location_ids of this RequestTimeFilterFastArrivalManyToOneSearch.
        :param transportation: The transportation of this RequestTimeFilterFastArrivalManyToOneSearch.
        :param travel_time: The travel_time of this RequestTimeFilterFastArrivalManyToOneSearch.
        :param arrival_time_period: The arrival_time_period of this RequestTimeFilterFastArrivalManyToOneSearch.
        :param properties: The properties of this RequestTimeFilterFastArrivalManyToOneSearch.
        """
        self.openapi_types = {
            'id': str,
            'arrival_location_id': str,
            'departure_location_ids': List[str],
            'transportation': RequestTransportationFast,
            'travel_time': int,
            'arrival_time_period': RequestArrivalTimePeriod,
            'properties': List[RequestTimeFilterFastProperty]
        }

        self.attribute_map = {
            'id': 'id',
            'arrival_location_id': 'arrival_location_id',
            'departure_location_ids': 'departure_location_ids',
            'transportation': 'transportation',
            'travel_time': 'travel_time',
            'arrival_time_period': 'arrival_time_period',
            'properties': 'properties'
        }

        self._id = id
        self._arrival_location_id = arrival_location_id
        self._departure_location_ids = departure_location_ids
        self._transportation = transportation
        self._travel_time = travel_time
        self._arrival_time_period = arrival_time_period
        self._properties = properties

    @classmethod
    def from_dict(cls, dikt: dict) -> 'RequestTimeFilterFastArrivalManyToOneSearch':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The RequestTimeFilterFastArrivalManyToOneSearch of this RequestTimeFilterFastArrivalManyToOneSearch.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this RequestTimeFilterFastArrivalManyToOneSearch.


        :return: The id of this RequestTimeFilterFastArrivalManyToOneSearch.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RequestTimeFilterFastArrivalManyToOneSearch.


        :param id: The id of this RequestTimeFilterFastArrivalManyToOneSearch.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def arrival_location_id(self):
        """Gets the arrival_location_id of this RequestTimeFilterFastArrivalManyToOneSearch.


        :return: The arrival_location_id of this RequestTimeFilterFastArrivalManyToOneSearch.
        :rtype: str
        """
        return self._arrival_location_id

    @arrival_location_id.setter
    def arrival_location_id(self, arrival_location_id):
        """Sets the arrival_location_id of this RequestTimeFilterFastArrivalManyToOneSearch.


        :param arrival_location_id: The arrival_location_id of this RequestTimeFilterFastArrivalManyToOneSearch.
        :type arrival_location_id: str
        """
        if arrival_location_id is None:
            raise ValueError("Invalid value for `arrival_location_id`, must not be `None`")

        self._arrival_location_id = arrival_location_id

    @property
    def departure_location_ids(self):
        """Gets the departure_location_ids of this RequestTimeFilterFastArrivalManyToOneSearch.


        :return: The departure_location_ids of this RequestTimeFilterFastArrivalManyToOneSearch.
        :rtype: List[str]
        """
        return self._departure_location_ids

    @departure_location_ids.setter
    def departure_location_ids(self, departure_location_ids):
        """Sets the departure_location_ids of this RequestTimeFilterFastArrivalManyToOneSearch.


        :param departure_location_ids: The departure_location_ids of this RequestTimeFilterFastArrivalManyToOneSearch.
        :type departure_location_ids: List[str]
        """
        if departure_location_ids is None:
            raise ValueError("Invalid value for `departure_location_ids`, must not be `None`")
        if departure_location_ids is not None and len(departure_location_ids) > 100000:
            raise ValueError("Invalid value for `departure_location_ids`, number of items must be less than or equal to `100000`")
        if departure_location_ids is not None and len(departure_location_ids) < 1:
            raise ValueError("Invalid value for `departure_location_ids`, number of items must be greater than or equal to `1`")

        self._departure_location_ids = departure_location_ids

    @property
    def transportation(self):
        """Gets the transportation of this RequestTimeFilterFastArrivalManyToOneSearch.


        :return: The transportation of this RequestTimeFilterFastArrivalManyToOneSearch.
        :rtype: RequestTransportationFast
        """
        return self._transportation

    @transportation.setter
    def transportation(self, transportation):
        """Sets the transportation of this RequestTimeFilterFastArrivalManyToOneSearch.


        :param transportation: The transportation of this RequestTimeFilterFastArrivalManyToOneSearch.
        :type transportation: RequestTransportationFast
        """
        if transportation is None:
            raise ValueError("Invalid value for `transportation`, must not be `None`")

        self._transportation = transportation

    @property
    def travel_time(self):
        """Gets the travel_time of this RequestTimeFilterFastArrivalManyToOneSearch.


        :return: The travel_time of this RequestTimeFilterFastArrivalManyToOneSearch.
        :rtype: int
        """
        return self._travel_time

    @travel_time.setter
    def travel_time(self, travel_time):
        """Sets the travel_time of this RequestTimeFilterFastArrivalManyToOneSearch.


        :param travel_time: The travel_time of this RequestTimeFilterFastArrivalManyToOneSearch.
        :type travel_time: int
        """
        if travel_time is None:
            raise ValueError("Invalid value for `travel_time`, must not be `None`")
        if travel_time is not None and travel_time > 14400:
            raise ValueError("Invalid value for `travel_time`, must be a value less than or equal to `14400`")
        if travel_time is not None and travel_time < 60:
            raise ValueError("Invalid value for `travel_time`, must be a value greater than or equal to `60`")

        self._travel_time = travel_time

    @property
    def arrival_time_period(self):
        """Gets the arrival_time_period of this RequestTimeFilterFastArrivalManyToOneSearch.


        :return: The arrival_time_period of this RequestTimeFilterFastArrivalManyToOneSearch.
        :rtype: RequestArrivalTimePeriod
        """
        return self._arrival_time_period

    @arrival_time_period.setter
    def arrival_time_period(self, arrival_time_period):
        """Sets the arrival_time_period of this RequestTimeFilterFastArrivalManyToOneSearch.


        :param arrival_time_period: The arrival_time_period of this RequestTimeFilterFastArrivalManyToOneSearch.
        :type arrival_time_period: RequestArrivalTimePeriod
        """
        if arrival_time_period is None:
            raise ValueError("Invalid value for `arrival_time_period`, must not be `None`")

        self._arrival_time_period = arrival_time_period

    @property
    def properties(self):
        """Gets the properties of this RequestTimeFilterFastArrivalManyToOneSearch.


        :return: The properties of this RequestTimeFilterFastArrivalManyToOneSearch.
        :rtype: List[RequestTimeFilterFastProperty]
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this RequestTimeFilterFastArrivalManyToOneSearch.


        :param properties: The properties of this RequestTimeFilterFastArrivalManyToOneSearch.
        :type properties: List[RequestTimeFilterFastProperty]
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")

        self._properties = properties
