# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.response_time_map_wkt_result import ResponseTimeMapWktResult
from openapi_server import util


class ResponseTimeMapWkt(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, results: List[ResponseTimeMapWktResult]=None):
        """ResponseTimeMapWkt - a model defined in OpenAPI

        :param results: The results of this ResponseTimeMapWkt.
        """
        self.openapi_types = {
            'results': List[ResponseTimeMapWktResult]
        }

        self.attribute_map = {
            'results': 'results'
        }

        self._results = results

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ResponseTimeMapWkt':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ResponseTimeMapWkt of this ResponseTimeMapWkt.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def results(self):
        """Gets the results of this ResponseTimeMapWkt.


        :return: The results of this ResponseTimeMapWkt.
        :rtype: List[ResponseTimeMapWktResult]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this ResponseTimeMapWkt.


        :param results: The results of this ResponseTimeMapWkt.
        :type results: List[ResponseTimeMapWktResult]
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")

        self._results = results
