/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIResponseTimeMap.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIResponseTimeMap::OAIResponseTimeMap(QString json) {
    init();
    this->fromJson(json);
}

OAIResponseTimeMap::OAIResponseTimeMap() {
    init();
}

OAIResponseTimeMap::~OAIResponseTimeMap() {
    this->cleanup();
}

void
OAIResponseTimeMap::init() {
    results = new QList<OAIResponseTimeMapResult*>();
    m_results_isSet = false;
}

void
OAIResponseTimeMap::cleanup() {
    if(results != nullptr) { 
        auto arr = results;
        for(auto o: *arr) { 
            delete o;
        }
        delete results;
    }
}

OAIResponseTimeMap*
OAIResponseTimeMap::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIResponseTimeMap::fromJsonObject(QJsonObject pJson) {
    
    ::OpenAPI::setValue(&results, pJson["results"], "QList", "OAIResponseTimeMapResult");
}

QString
OAIResponseTimeMap::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIResponseTimeMap::asJsonObject() {
    QJsonObject obj;
    if(results->size() > 0){
        toJsonArray((QList<void*>*)results, obj, "results", "OAIResponseTimeMapResult");
    }

    return obj;
}

QList<OAIResponseTimeMapResult*>*
OAIResponseTimeMap::getResults() {
    return results;
}
void
OAIResponseTimeMap::setResults(QList<OAIResponseTimeMapResult*>* results) {
    this->results = results;
    this->m_results_isSet = true;
}


bool
OAIResponseTimeMap::isSet(){
    bool isObjectUpdated = false;
    do{
        if(results->size() > 0){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

