/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIResponseTimeFilterPostcodesResult.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIResponseTimeFilterPostcodesResult::OAIResponseTimeFilterPostcodesResult(QString json) {
    init();
    this->fromJson(json);
}

OAIResponseTimeFilterPostcodesResult::OAIResponseTimeFilterPostcodesResult() {
    init();
}

OAIResponseTimeFilterPostcodesResult::~OAIResponseTimeFilterPostcodesResult() {
    this->cleanup();
}

void
OAIResponseTimeFilterPostcodesResult::init() {
    search_id = new QString("");
    m_search_id_isSet = false;
    postcodes = new QList<OAIResponseTimeFilterPostcode*>();
    m_postcodes_isSet = false;
}

void
OAIResponseTimeFilterPostcodesResult::cleanup() {
    if(search_id != nullptr) { 
        delete search_id;
    }
    if(postcodes != nullptr) { 
        auto arr = postcodes;
        for(auto o: *arr) { 
            delete o;
        }
        delete postcodes;
    }
}

OAIResponseTimeFilterPostcodesResult*
OAIResponseTimeFilterPostcodesResult::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIResponseTimeFilterPostcodesResult::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&search_id, pJson["search_id"], "QString", "QString");
    
    
    ::OpenAPI::setValue(&postcodes, pJson["postcodes"], "QList", "OAIResponseTimeFilterPostcode");
}

QString
OAIResponseTimeFilterPostcodesResult::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIResponseTimeFilterPostcodesResult::asJsonObject() {
    QJsonObject obj;
    if(search_id != nullptr && *search_id != QString("")){
        toJsonValue(QString("search_id"), search_id, obj, QString("QString"));
    }
    if(postcodes->size() > 0){
        toJsonArray((QList<void*>*)postcodes, obj, "postcodes", "OAIResponseTimeFilterPostcode");
    }

    return obj;
}

QString*
OAIResponseTimeFilterPostcodesResult::getSearchId() {
    return search_id;
}
void
OAIResponseTimeFilterPostcodesResult::setSearchId(QString* search_id) {
    this->search_id = search_id;
    this->m_search_id_isSet = true;
}

QList<OAIResponseTimeFilterPostcode*>*
OAIResponseTimeFilterPostcodesResult::getPostcodes() {
    return postcodes;
}
void
OAIResponseTimeFilterPostcodesResult::setPostcodes(QList<OAIResponseTimeFilterPostcode*>* postcodes) {
    this->postcodes = postcodes;
    this->m_postcodes_isSet = true;
}


bool
OAIResponseTimeFilterPostcodesResult::isSet(){
    bool isObjectUpdated = false;
    do{
        if(search_id != nullptr && *search_id != QString("")){ isObjectUpdated = true; break;}
        if(postcodes->size() > 0){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

