/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIRequestTimeMapProperty.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIRequestTimeMapProperty::OAIRequestTimeMapProperty(QString json) {
    init();
    this->fromJson(json);
}

OAIRequestTimeMapProperty::OAIRequestTimeMapProperty() {
    init();
}

OAIRequestTimeMapProperty::~OAIRequestTimeMapProperty() {
    this->cleanup();
}

void
OAIRequestTimeMapProperty::init() {
}

void
OAIRequestTimeMapProperty::cleanup() {
}

OAIRequestTimeMapProperty*
OAIRequestTimeMapProperty::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIRequestTimeMapProperty::fromJsonObject(QJsonObject pJson) {
}

QString
OAIRequestTimeMapProperty::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIRequestTimeMapProperty::asJsonObject() {
    QJsonObject obj;

    return obj;
}


bool
OAIRequestTimeMapProperty::isSet(){
    bool isObjectUpdated = false;
    do{
    }while(false);
    return isObjectUpdated;
}
}

