/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIRequestTimeFilterPostcodes.h
 *
 * 
 */

#ifndef OAIRequestTimeFilterPostcodes_H
#define OAIRequestTimeFilterPostcodes_H

#include <QJsonObject>


#include "OAIRequestTimeFilterPostcodesArrivalSearch.h"
#include "OAIRequestTimeFilterPostcodesDepartureSearch.h"
#include <QList>

#include "OAIObject.h"

namespace OpenAPI {

class OAIRequestTimeFilterPostcodes: public OAIObject {
public:
    OAIRequestTimeFilterPostcodes();
    OAIRequestTimeFilterPostcodes(QString json);
    ~OAIRequestTimeFilterPostcodes() override;
    void init();

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAIRequestTimeFilterPostcodesDepartureSearch> getDepartureSearches() const;
    void setDepartureSearches(const QList<OAIRequestTimeFilterPostcodesDepartureSearch> &departure_searches);

    QList<OAIRequestTimeFilterPostcodesArrivalSearch> getArrivalSearches() const;
    void setArrivalSearches(const QList<OAIRequestTimeFilterPostcodesArrivalSearch> &arrival_searches);

    virtual bool isSet() const override;

private:
    QList<OAIRequestTimeFilterPostcodesDepartureSearch> departure_searches;
    bool m_departure_searches_isSet;

    QList<OAIRequestTimeFilterPostcodesArrivalSearch> arrival_searches;
    bool m_arrival_searches_isSet;

};

}

#endif // OAIRequestTimeFilterPostcodes_H
