/**
 * TravelTime Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@igeolise.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIResponseFaresBreakdownItem.h
 *
 * 
 */

#ifndef OAIResponseFaresBreakdownItem_H
#define OAIResponseFaresBreakdownItem_H

#include <QJsonObject>


#include "OAIResponseFareTicket.h"
#include "OAIResponseTransportationMode.h"
#include <QList>

#include "OAIObject.h"

namespace OpenAPI {

class OAIResponseFaresBreakdownItem: public OAIObject {
public:
    OAIResponseFaresBreakdownItem();
    OAIResponseFaresBreakdownItem(QString json);
    ~OAIResponseFaresBreakdownItem() override;
    void init();

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAIResponseTransportationMode> getModes() const;
    void setModes(const QList<OAIResponseTransportationMode> &modes);

    QList<qint32> getRoutePartIds() const;
    void setRoutePartIds(const QList<qint32> &route_part_ids);

    QList<OAIResponseFareTicket> getTickets() const;
    void setTickets(const QList<OAIResponseFareTicket> &tickets);

    virtual bool isSet() const override;

private:
    QList<OAIResponseTransportationMode> modes;
    bool m_modes_isSet;

    QList<qint32> route_part_ids;
    bool m_route_part_ids_isSet;

    QList<OAIResponseFareTicket> tickets;
    bool m_tickets_isSet;

};

}

#endif // OAIResponseFaresBreakdownItem_H
